### ISSUE TITLE
Why README and examples still dont use the python 3.5 `async def` style?

### ISSUE THREAD

**Issue by pahaz** [aio-libs/aioredis#102]
like `aiomysql` and `aiopg`. Some examples in https://github.com/aio-libs/aioredis/commit/bf6acf79aea708018783ecc26407fa8aee74eea7 uses `async def` style.

 - [ ] README refactoring
 - [ ] examples refactoring

**Comment by popravich** [comment]
Hi, @pahaz 
It does not make much sense to change `@coroutine & yield from` to `async def & await` in readme.
`aioredis` support python3.3/3.4+ which has no native coroutine so, I guess, using `@coroutine` and `yield from`s is more verbose regarding support of those python versions.

**Comment by pahaz** [comment]
Many other `aio-libs` use new style. I think that new still is more preferable in examples. (my opinion)

**Comment by popravich** [comment]
I still don't follow. Why?
