### ISSUE TITLE
Any plan to support Redis Sentinel?

### ISSUE THREAD

**Issue by ciscorn** [aio-libs/aioredis#104]
Do you have any plan to support Redis Sentinel?

I just wrote an experimental implementation of Sentinel client.
https://github.com/ciscorn/aioredis/commit/dd07fcdb90c409147962cee26cc2670b5fbad35c

**Comment by popravich** [comment]
Hi, I plan to support Redis Sentinel.

There is also other branch [jettify/aioredis](https://github.com/jettify/aioredis/tree/sentinel).
But there are no any Pull Requests yet.

**Comment by jettify** [comment]
Hi our solution is working and we are using it. I have plan to make PR
soon, maybe in the middle of next week.

**Comment by ciscorn** [comment]
OK. Does that support connection pooling?

**Comment by popravich** [comment]
Sentinel feature is now available in master branch; still under development but already working.
