### ISSUE TITLE
RedisConnection.execute should raise custom exception when server is unreachable.

### ISSUE THREAD

**Issue by hotsyk** [aio-libs/aioredis#108]
Currently, RediscConnection.execute asserting live connection: https://github.com/aio-libs/aioredis/blob/master/aioredis/connection.py#L211 

As a result, if the connection to server lost (server restarted, or network lost), AssertionError will be raised. 
This leads to requirement to catch AssertionError if client would like to reconnect to server, and this is not correct way to catch this - more appropriate way would be to raise custom exception here and catch this specific exception in the client.

**Comment by jettify** [comment]
Good point, also worth mention that asserts does not work if `python` run with `-O` or `-OO` flags

**Comment by asvetlov** [comment]
@hotsyk would you provide a PR for replacement `AssertionError` with custom exception class inherited from `RedisError`?

A test is required, it may use mocks though. Redis server stopping is not needed, just simulate the case by mocking.

**Comment by popravich** [comment]
It looks like `execute_pubsub` is missing even assertion, need to fix this too.

**Comment by hotsyk** [comment]
Will do in a few days

**Comment by popravich** [comment]
Great, thanks

**Comment by popravich** [comment]
`execute_pubsub` fixed
