### ISSUE TITLE
Transactions and not transaction commands in one connection

### ISSUE THREAD

**Issue by tumb1er** [aio-libs/aioredis#110]
On a highly-loaded process with single connection I've got an `AssertionError from `MultiExec._do_execute`.
```python
assert len(results) == len(waiters), (results, waiters)
# results, waiters looked like: 
([('OK', 0)], [])
```
It seems, that when I use multi like this:
```python
with (yield from self.tr_lock):  # asyncio.Lock                            
     tr = self.redis.multi_exec()                             
     tr.hmset(self.data_key, *chunk_data)        
     tr.zadd(self.chunks_key, *items)            
     yield from tr.execute()
```
other green threads somehow can add other commands to this connection.
Is it possible for reconnecting redis? 
```python
self.redis = yield from aioredis.create_reconnecting_redis(...)
```

Should I always use separate redis connection for transaction-only interactions?
By the way, the whole application freezes until Ctrl+C pressed.

**Comment by popravich** [comment]
Hmm...
This looks very strange, need to look into it...

**Comment by popravich** [comment]
Can you make a test to reproduce it?

**Comment by tumb1er** [comment]
I'll try to write an example script next week, because it's probably a race-condition effect.

**Comment by tumb1er** [comment]
Well, transaction and standalone commands itself don't break anything.
I wrote a simple script, that executes 120 transactions and 1200 standalone redis commands with single redis connection, and couldn't reproduce behavior described above.
Than I added "cancel monkey", than randomly cancels and re-launches green cycles, and in less than a minute script stucked with AssertionError. All other green cycles also stopped, except "cancel monkey".

Script itself is here: https://gist.github.com/anonymous/4ea757a6690ccfb27d99

Maybe `transaction.execute()` should be [shielded](https://docs.python.org/3/library/asyncio-task.html#asyncio.shield) from cancellation?

**Comment by popravich** [comment]
Thanks, I will take a look

**Comment by tumb1er** [comment]
```python
yield from asyncio.shield(transaction.execute())
```

And no more freezes. Is PR without any tests appropriate for this bugfix?

**Comment by asvetlov** [comment]
Interesting, I've added `shield` to aiopg in December

**Comment by popravich** [comment]
Its a bit deeper problem, but I almost have a fix.

**Comment by popravich** [comment]
@tumb1er, the issue should be fixed now, can you check it with latest version from master?

**Comment by tumb1er** [comment]
@popravich works for me now:
```sh
$ pip install git+https://github.com/aio-libs/aioredis.git
Collecting git+https://github.com/aio-libs/aioredis.git
  Cloning https://github.com/aio-libs/aioredis.git to /tmp/pip-l10d4d8q-build
Requirement already satisfied (use --upgrade to upgrade): hiredis in /home/tumbler/virtualenv/mitya/lib/python3.4/site-packages (from aioredis==0.2.5)
Installing collected packages: aioredis
  Found existing installation: aioredis 0.2.4
    Uninstalling aioredis-0.2.4:
      Successfully uninstalled aioredis-0.2.4
  Running setup.py install for aioredis ... done
Successfully installed aioredis-0.2.5

```
