### ISSUE TITLE
Cluster compatible tests

### ISSUE THREAD

**Issue by the-panda** [aio-libs/aioredis#112]
To run the tests in a cluster environment I want to make sure that all used keys map to the same key slot. I think there are two solutions based on hash tags:

- Use 'key' whenever possible and 'non-existing-{key}', '{key}-1' '{key}-2' etc. when more keys are needed. Send a FLUSHALL command before each test to make sure that tests don't interfere (FLUSHALL  is already used by some tests).

- Use a separate key for each test, e.g. '{key}:set:expire'. Send FLUSHALL once at the start of the test suite.

What are your thoughts?

**Comment by popravich** [comment]
Hi, both solutions are fine, but I personally would prefer second one, ie:
using keys prefixed with specific hash tags and sending FLUSHALL only when needed.

**Comment by the-panda** [comment]
I have now modified most of your tests so that they run successfully on a cluster. I changed keys to something like {key:delete}:1 whenever multiple keys are used on the same node. The remaining tests are skipped because the tested functionality is not meaningful on a cluster or has not yet been implemented by the cluster code.

You can find my pull request to trezorg's fork here: https://github.com/trezorg/aioredis/pull/1

To reduce the risk of merge conflicts while the cluster code is still in development I could create a pull request to your repository which would only include my changes to the *_commands_test.py files (and a bit in _testutils.py), but no actual cluster code. Do you think this is a good idea?

Besides, I still think that it would be better to flush the database before each test. It would make the tests independent and would allow to remove many delete-commands at the beginning of various tests.
