### ISSUE TITLE
Pubsub with listen to all subscribed channels?

### ISSUE THREAD

**Issue by Artimi** [aio-libs/aioredis#127]
Hi,

I would like to use pubsub where I dynamically add and remove channels to subscriber. Subscriber then should listen to all of them and wait for first incoming message from whichever channel. Basically, I want to have some object like this:

``` python
import asyncio
import aioredis

class RedisSubscriber:
    @asyncio.coroutine
    async def connect(self):
        self._connection = await aioredis.create_redis(('localhost', 6379))

    @asyncio.coroutine
    async def subscribe(self, channel):
        await self._connection.subscribe(channel)

    @asyncio.coroutine
    async def get(self):
        channel, reply = await self._connection.listen()  # this is made up
        return channel, reply
```

I want to just call `get` in loop and get replies with their channels even when I add new channels to subscribe after `get` was called. Is something similar possible with `aioredis`?

**Comment by popravich** [comment]
Hi, @Artimi 
You can simply create one subscriber and subscribe to pattern `*`
and you'll receive all messages for all channels (including channel name to which message is published)

**Comment by popravich** [comment]
See [this test](https://github.com/aio-libs/aioredis/blob/master/tests/pubsub_commands_test.py#L70-L83) for example

**Comment by Artimi** [comment]
Hi @popravich 
Thank you for response. I now see that my question is misleading. In my setup I want several subscribers that will listen to subset of channels available in pubsub. For example I will have channels `1, 2, 3, 4` and two subscribers like this:
```
s1: 1, 2
s2: 4
```
I could subscribe to more channels and listen to all of them with `asyncio.gather` but I would need to somehow reset `get` function from my example.

**Comment by bharling** [comment]
+1 from me, It would be nice to have a way to just subscribe a single listener coroutine to a dynamic set of channels and receive all messages on those channels without needing to specify which we're listening to. 

In my project, I have a separate system managing which channels are subscribed by a given listening coroutine and it won't know in advance what those channels are. The subscriptions are also added and removed fairly frequently. 

redis-py does allow this I think? ( example linked below ). In their implementation there appears to just be a 'pubsub' object that is channel agnostic and can subscribe and unsubscribe to any number of channels as needed. This is the behaviour I'm looking for really, but in async 👍 

https://gist.github.com/jobliz/2596594

**Comment by khazhyk** [comment]
+1, I passed on this library earlier due to lack of being able to subscribe to multiple patterns on a single listener. Listening to '*' is not ideal, and having to have many channel listeners is also not ideal. A system where a subscriber can subscribe to multiple explicit channels (and only those channels) would be great.

**Comment by popravich** [comment]
Hi @Artimi, @bharling, @khazhyk 
Sorry for long silence.
I have just made a new release `v0.3.0` including requested pub/sub feature — aioredis.pubsub.Receiver.
It can be used as follows:
```python
from aioredis.pubsub import Receiver

mpsc = Receiver()

async def single_reader():
    while await mpsc.wait_message():
        sender, message = await mpsc.get()
        print("Got message {!r} from {!r}", message, sender.name)
# run reader
asyncio.ensure_future(single_reader())
# use mpsc to add channles
await redis.subscribe(
    mpsc.channel('channel:1'),
    mpsc.channel('channel:3'))
# ...and/or patterns
await redis.psubscribe(mpsc.channel('patt*'))
```

**Comment by popravich** [comment]
I'm closing this, if you find any issues using this please open a new one.

**Comment by bharling** [comment]
Thanks - missed your reply, but thanks for the fix, will have a look when i get a chance

**Comment by Vytautas-RA** [comment]
> Hi @Artimi, @bharling, @khazhyk Sorry for long silence. I have just made a new release `v0.3.0` including requested pub/sub feature — aioredis.pubsub.Receiver. It can be used as follows:
> 
> ```python
> from aioredis.pubsub import Receiver
> 
> mpsc = Receiver()
> 
> async def single_reader():
>     while await mpsc.wait_message():
>         sender, message = await mpsc.get()
>         print("Got message {!r} from {!r}", message, sender.name)
> # run reader
> asyncio.ensure_future(single_reader())
> # use mpsc to add channles
> await redis.subscribe(
>     mpsc.channel('channel:1'),
>     mpsc.channel('channel:3'))
> # ...and/or patterns
> await redis.psubscribe(mpsc.channel('patt*'))
> ```

Hi.
       I've got error on this example: ModuleNotFoundError: No module named 'aioredis.pubsub'. Do I need to install something more?

**Comment by Andrew-Chen-Wang** [comment]
@Vytautas-RA make sure you install aioredis==1.3.1 as it has completely separate files. We are currently on aioredis==2.0.0.

**Comment by Vytautas-RA** [comment]
> aioredis==1.3.1

Thanks. It works.
But I do not understand how to initialize redis variable in you example.

**Comment by Andrew-Chen-Wang** [comment]
You'll need to read the docs to prior version. You can go to our docs site and change the version. Or you can go to GitHub and change the branch to the tag 1.3.1
