### ISSUE TITLE
write benchmarks

### ISSUE THREAD

**Issue by popravich** [aio-libs/aioredis#13]

**Comment by popravich** [comment]
Some benchmarks added here — https://github.com/popravich/python-redis-benchmark

**Comment by asvetlov** [comment]
I suggest moving the repo into aio-libs

**Comment by asvetlov** [comment]
Just for better visibility

**Comment by pfreixes** [comment]
Could you add in the README.md the results that you got? Will help to have an idea of the status without the need to run them in local.

**Comment by popravich** [comment]
Well, yeah, I will add some results to readme, it all just need more time to write some notes on result numbers.

**Comment by popravich** [comment]
updated [repo](https://github.com/popravich/python-redis-benchmark#tests-and-results) with some results.
