### ISSUE TITLE
Need PyPI version/release for pool closure feature

### ISSUE THREAD

**Issue by brandond** [aio-libs/aioredis#133]
I have some code that uses `pool.close()` to cleanly shutdown client connections. Unfortunately this is only available by installing the module from this repo. Do you have an ETA on when you will version bump and release to PyPI?

**Comment by popravich** [comment]
Hi, @brandond, I will release today

**Comment by popravich** [comment]
Bump! https://pypi.python.org/pypi/aioredis/0.2.8
