### ISSUE TITLE
please include tests, docs and examples in the tarball

### ISSUE THREAD

**Issue by p1otr** [aio-libs/aioredis#134]
Please include tests, docs and examples in the tarball released on PyPI

**Comment by popravich** [comment]
Why?

**Comment by p1otr** [comment]
because I want to use them in my Debian package (tests during build and docs/examples as a documentation for those who don't want to use online docs)

**Comment by popravich** [comment]
You can use tag releases on github they include everything

**Comment by asvetlov** [comment]
@popravich you may pus everything into tarball.
Wheel builder strips everything but code and metainformation.
All modern pip versions try to download wheel first if present.
So most likely user will download tiny wheel file but in tar.gz he will get everything related to the project.

**Comment by popravich** [comment]
fixed in v0.2.9
