### ISSUE TITLE
Channel object is not documented

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aioredis#137]
From docs reading it's not obvious what object is returned by `redis.subscribe()` call and what attributes/methods the object has.
The most important attrs are `.get()` and `.iter()` but all public api worth to be documented.

**Comment by popravich** [comment]
The `Channel` object is [documented](http://aioredis.readthedocs.io/en/v0.2.8/api_reference.html#aioredis-channel).
However, it is not mentioned in pub/sub methods

**Comment by asvetlov** [comment]
Now the issue can be closed, isn't it?
