### ISSUE TITLE
Py 3.5.2: hiredis fails to install

### ISSUE THREAD

**Issue by Kentoseth** [aio-libs/aioredis#171]
I am cross-posting this, so that people are aware of the issue both here and here: https://github.com/redis/hiredis-py/issues/49

If you want to make use of the new Python 3.5 features for the asyncio-lib, the inability to install `hiredis` will prevent you from doing so.

**Comment by popravich** [comment]
[travis builds](https://travis-ci.org/aio-libs/aioredis/builds/179388364) are all ok (from python 3.3 to 3.6-dev).
You are missing `Python.h` file or maybe it is inaccessible...

**Comment by Kentoseth** [comment]
I am dealing with this issue directly with the hiredis-py team.

I will update this thread once a solution is found.

**Comment by Kentoseth** [comment]
Please see link (above), as the issue is now solved.

For people who need a quick answer, it is:

`sudo apt-get install python3.5-dev`

(remember to have a PPA with this dev package, if your host-OS does not ship with Python 3.5 by default).
