### ISSUE TITLE
Installation on Windows

### ISSUE THREAD

**Issue by dland512** [aio-libs/aioredis#178]
I'm trying to install on Windows 10 and am running into an error I can't figure out. It appears to be related to hiredis, which as far as I can tell should install on Windows. Has anyone run into this?

> C:\\> pip3 install aioredis
> Collecting aioredis
>   Using cached aioredis-0.2.9-py3-none-any.whl
> Collecting hiredis (from aioredis)
>   Using cached hiredis-0.2.0.tar.gz
> Building wheels for collected packages: hiredis
>   Running setup.py bdist_wheel for hiredis ... error
>   Complete output from command c:\code\torus\venv\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Dave\\AppData\\Local\\Temp\\pip-build-a8cyfjue\\hiredis\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\Dave\AppData\Local\Temp\tmpwtzhpc1xpip-wheel- --python-tag cp34:
>   running bdist_wheel
>   running build
>   running build_py
>   creating build
>   creating build\lib.win-amd64-3.4
>   creating build\lib.win-amd64-3.4\hiredis
>   copying hiredis\version.py -> build\lib.win-amd64-3.4\hiredis
>   copying hiredis\__init__.py -> build\lib.win-amd64-3.4\hiredis
>   running build_clib
>   building 'hiredis_for_hiredis_py' library
>   error: INCLUDE environment variable is empty
> 
>   ----------------------------------------
>   Failed building wheel for hiredis
>   Running setup.py clean for hiredis
> Failed to build hiredis
> Installing collected packages: hiredis, aioredis
>   Running setup.py install for hiredis ... error
>     Complete output from command c:\code\torus\venv\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Dave\\AppData\\Local\\Temp\\pip-build-a8cyfjue\\hiredis\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Dave\AppData\Local\Temp\pip-0keqj3wf-record\install-record.txt --single-version-externally-managed --compile --install-headers c:\code\torus\venv\include\site\python3.4\hiredis:
>     running install
>     running build
>     running build_py
>     creating build
>     creating build\lib.win-amd64-3.4
>     creating build\lib.win-amd64-3.4\hiredis
>     copying hiredis\version.py -> build\lib.win-amd64-3.4\hiredis
>     copying hiredis\__init__.py -> build\lib.win-amd64-3.4\hiredis
>     running build_clib
>     building 'hiredis_for_hiredis_py' library
>     error: INCLUDE environment variable is empty
> 
>     ----------------------------------------
> Command "c:\code\torus\venv\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Dave\\AppData\\Local\\Temp\\pip-build-a8cyfjue\\hiredis\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Dave\AppData\Local\Temp\pip-0keqj3wf-record\install-record.txt --single-version-externally-managed --compile --install-headers c:\code\torus\venv\include\site\python3.4\hiredis" failed with error code 1 in C:\Users\Dave\AppData\Local\Temp\pip-build-a8cyfjue\hiredis\

**Comment by popravich** [comment]
Hi, @dland512 
I think you need msvc compiler to build hiredis

**Comment by dland512** [comment]
Okay, I'll look into that. Thank you.

**Comment by Yrysbek03** [comment]
how did you repair this poblem ? i have this problem too. but i don't now how repair this.
