### ISSUE TITLE
New Pool documentation

### ISSUE THREAD

**Issue by popravich** [aio-libs/aioredis#182]
TODO:
* [x] Update examples and check code samples in docs
* [x] Add *upgrading from 0.x to 1.0* instructions
* [x] Add notes on known bugs/limitations/expected behavior

**Comment by dpereira** [comment]
Not sure if it will be already covered by this, but the 1st example here:

https://aioredis.readthedocs.io/en/v0.3.0/api_reference.html#connections-pool

seems to be missing a call to 'acquire' before 'execute'.

**Comment by popravich** [comment]
Yeap, its probably example for `master` branch not for `v0.3`
