### ISSUE TITLE
Add connect timeout

### ISSUE THREAD

**Issue by popravich** [aio-libs/aioredis#184]
aioredis may stuck (pool especially) if Redis server is not responsive.

(don't know why nobody notice it is missing)

**Comment by popravich** [comment]
TODO:
* [ ] add connect timeout
* [ ] test with slow connection

**Comment by SeavantUUz** [comment]
I met some problem, but I could not support your suggestion. What I had seen, although redis server is fine, aioredis got stuck too.

In redis-py, why you could pass an optional argument to pool, is redis-py chose block queue as its pool's implement. The timeout argument actually is used to tell pool the queue had been empty for specific time. aioredis used deque as its pool's implement, so you can't pass a timeout.

Another time out argument is `socket_timeout` or `socket_keepalive` and so on. I'm not sure whether they are good choices.

**Comment by popravich** [comment]
What I mean is that aioredis can stuck for some time (probably long enough) when using pool,
basically, the call to `ConnectionsPool._create_new_connection()` need to have some timeout
otherwise it will block the whole pool.

**Comment by pfreixes** [comment]
We might be having this issue, I can work on a fix ASAP

**Comment by pfreixes** [comment]
This can be closed.
