### ISSUE TITLE
implement pure-python fallback redis response parser

### ISSUE THREAD

**Issue by popravich** [aio-libs/aioredis#2]
for case when `hiredis` is not available

**Comment by popravich** [comment]
Won't do. hiredis is much faster. It would sound more reasonable to improve hiredis parser.

**Comment by kernel0** [comment]
because hiredis package does not support windows, windows user can't use aioredis. Is there workaround?

**Comment by popravich** [comment]
hmm...

**Comment by popravich** [comment]
ok. I'll consider this

**Comment by kernel0** [comment]
thank you! :+1:
