### ISSUE TITLE
wait_message() with timeout

### ISSUE THREAD

**Issue by DeoLeung** [aio-libs/aioredis#204]
Hi,

I would like channel `wait_message` method support timeout feature, or anyone knows some workaround?

**Comment by a-sk** [comment]
You can use [async-timeout](https://github.com/aio-libs/async-timeout), I think.

**Comment by DeoLeung** [comment]
@a-sk yes, just came across that, would give it a try

**Comment by DeoLeung** [comment]
FYI,

tornado user: use [gen.with_timeout](http://www.tornadoweb.org/en/stable/gen.html#tornado.gen.with_timeout)
