### ISSUE TITLE
aioredis with tornado

### ISSUE THREAD

**Issue by ivanperelivskiy** [aio-libs/aioredis#206]
Hi, 

Unfortunately i could not find any mention about usage with python 3 async/await and tornado. Could you please share some info on how to use, more specifically how to create a connection within torando ioloop.

Thank you.

**Comment by popravich** [comment]
Hi, please take a look at this example — [rudyryk/python-samples/hello_tornado/hello_asyncio.py](https://github.com/rudyryk/python-samples/blob/57b195ee10aea9ed36a9f97a5bfe9369c9390ca5/hello_tornado/hello_asyncio.py)

**Comment by ivanperelivskiy** [comment]
Спасибо!

**Comment by Inferato** [comment]
> In case anyone else stumbles upon this thread, here is an alternative solution:
> 
> ```
>     conn = await aioredis.create_connection(REDIS_ADDRESS,
>                                             loop=IOLoop.current().asyncio_loop,
>                                             encoding='utf-8')
> ```
> 
> This works with tornado >= 5.0.
> 
> Best wishes.

Dude, u r my superhero xD

**Comment by DachuanZhao** [comment]
> In case anyone else stumbles upon this thread, here is an alternative solution:
> 
> ```
>     conn = await aioredis.create_connection(REDIS_ADDRESS,
>                                             loop=IOLoop.current().asyncio_loop,
>                                             encoding='utf-8')
> ```
> 
> This works with tornado >= 5.0.
> 
> Best wishes.

Could you please give a full example here ?  : )
