### ISSUE TITLE
await redis.hgetall(key) rasie concurrent.futures._base.CancelledError

### ISSUE THREAD

**Issue by larry-dev** [aio-libs/aioredis#247]
`result = await redis.hgetall(key)`
this key in the 'redis‘

but raise concurrent.futures._base.CancelledError:
`Unable to display children:Error resolving variables Traceback (most recent call last):
  File "/Users/ss/Documents/ykrealtime/rtgame/logics/userlogic.py", line 100, in leave_room
    result = await redis.hgetall(key)
  File "/Users/ss/Documents/ykrealtime/venv/lib/python3.6/site-packages/aioredis/util.py", line 77, in wait_make_dict
    res = yield from fut`

**Comment by popravich** [comment]
Apparently task executing `redis.hget` was cancelled

**Comment by larry-dev** [comment]
but,why it was cancelled.i don't understand.
and this is not always a mistake

**Comment by popravich** [comment]
It is really hard to say looking at a single line of code)
From what I can see, `hgetall` request was slow so the task cancellation bubbled up in call to redis.
Do you have a timeout for that task?

**Comment by larry-dev** [comment]
sorry,it is my problem.

**Comment by popravich** [comment]
no problem
