### ISSUE TITLE
What's changed in 0.3.3?

### ISSUE THREAD

**Issue by samuelcolvin** [aio-libs/aioredis#258]
v0.3.3 has no release or tag so I can't find which commit it refers to and there's no reference to it in CHANGES.txt.

Before I upgrade, please can you describe what has changed and/or add a tag referring to the release?

**Comment by samuelcolvin** [comment]
ok, just seen the tag. still changes.txt update would be good

**Comment by popravich** [comment]
have you checked branch `v0.3`?

**Comment by popravich** [comment]
https://aioredis.readthedocs.io/en/v0.3.3/releases.html#id1
