### ISSUE TITLE
1.0 release

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aioredis#267]
1.0 beta has very handy `aioredis.create_redis_pool()` API.
@popravich do you have a schedule for 1.0 release?

**Comment by popravich** [comment]
Oh, there is no particular schedule.
Here is some tasks to complete the release:
* [ ] Documentation
  * [ ] Write migration notes.
  * [ ] Write Sentinel documentation.
  * [ ] Update Pool docstrings.
* [ ] Integration tests — write tests to check that new pool acts as before in old code.
* [ ] Link benchmarks (put somewhere in docs)
  * [ ] add network tests

Hopefully I'll manage to free some time for this.

**Comment by asvetlov** [comment]
Ping

**Comment by popravich** [comment]
The wheels are rolling!
I have re-scheduled v1.0 milestone to next Friday, 17th and full of confidence to release it then.

**Comment by popravich** [comment]
I'm glad to announce that aioredis `v1.0` has been published!

**Comment by pfreixes** [comment]
Congrats!
