### ISSUE TITLE
Pub/Sub mode

### ISSUE THREAD

**Issue by popravich** [aio-libs/aioredis#27]
This must be implemented in connection.

TODO:
* add separate methods for subscribing to channels/patterns;
* mark connection as "in subscribe" mode;
* add check to `execute` method that connection is not "in subscribe" mode;
* check if connection "in subscribe" in `_read_data` method and start other reader task;
* create "other reader task" (need better name) that will wait for messages (similar way as `asyncio.as_completed()`;

result must be something like:
```python
ok = yield from conn.subscribe('channel:1', 'channel:2')
for waiter in conn.wait_messages(): # (this is the "other reader task" that need a good name)
    data = yield from waiter
    # do something
```

As for high-level part Redis docs have a good hint: http://redis.io/topics/pubsub (Client library implementation hints)

**Comment by metathink** [comment]
+1 I'd love to see this feature implemented.

**Comment by dveselov** [comment]
bump?

**Comment by popravich** [comment]
Hi guys,
This is in progress, very slow progress.
I think I'll implement it in a week or two.

**Comment by Natim** [comment]
Hello, I need it as well :)

**Comment by Natim** [comment]
Apparently https://github.com/jonathanslenders/asyncio-redis does it already.

**Comment by kernel0** [comment]
I'm really need it!

**Comment by popravich** [comment]
almost there)

**Comment by popravich** [comment]
So, its in master.
docs and hi-level interface is still TBD.
currently the usage as follows:
```python
sub = yield from create_connection(...)

yield from sub.execute('subscribe', 'chan:1', 'chan:2', 'etc')

@asycnio.coroutine
def worker(queue):
    while True:
        msg = yield from queue.get()
        # Process messsage....
asyncio.async(worker(sub.pubsub_channels['chan:1']))
# or
while True:
    msg = yield from sub.pubsub_channels['chan:2'].get()
    # process message...
```

**Comment by popravich** [comment]
There is still things that need to be done and I may change this interface a bit,
but you still can test it.

**Comment by kernel0** [comment]
thank you!! I will use as follows until complete of hi-level interface:
```python
    pool = yield from aioredis.create_pool(('localhost',6379))
    with (yield from pool) as redis:
        yield from redis.connection.execute('subscribe', 'chan1')
        while True:
            msg = yield from redis.connection.pubsub_channels['chan1'].get()
            print(msg)
```
ps : I hope this wonderful feature is distributed to pypi!

**Comment by popravich** [comment]
released

**Comment by kernel0** [comment]
congratulation!
