### ISSUE TITLE
Implement custom StreamReader

### ISSUE THREAD

**Issue by popravich** [aio-libs/aioredis#271]
Rationale:
* Get rid of bouble buffering (`data from socket -> asyncio.StreamReader.buffer -> hiredis.Reader.buffer`);
  our StreamReader can feed data directly to parser (hiredis or PyReader);
* Step over this issue — http://bugs.python.org/issue30861;

Some specs:
* must inherit from `asyncio.StreamReader`;
* `read...`-family functions should probably raise an error (RuntimeError);
* provide `async def read_response()` method waiting and returning either valid response
or raising an error (protocol error, canceled, closed, etc) (maybe some other method name);

**Comment by pfreixes** [comment]
Challenge accepted.

**Comment by pfreixes** [comment]
Just one note about that task, the implementation of that new Reader class **won't get rid of the double buffer flow**. In any case, the new implementation will replace the official class provided by asyncio for a new one but the double step must remain there for many reasons.

are we in the same page?

Further, we could think in implement the Reader class - will become a bunch of code lines - in Cython. Theoretically, in an environment with `uvloop` and `hiredis` must speed up `aioredis`.

**Comment by pfreixes** [comment]
Forget it, we will remove the double buffer and one coroutine step.
