### ISSUE TITLE
Let's drop Python 3.3 & 3.4 support

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aioredis#304]
Python 3.3 is too old and not maintained anymore.
I doubt if anybody runs aioredis on this version.

Honestly it's time to drop 3.4 too -- the next aiohttp release most likely will support python 3.5+ only.

**Comment by hugovk** [comment]
The numbers support this.

Here's the pip installs for aioredis from PyPI for the last month:
```
$ pypinfo --percent --pip aioredis pyversion
python_version percent download_count
-------------- ------- --------------
3.5              62.8%         16,277
3.6              35.7%          9,250
3.4               0.6%            152
2.7               0.5%            135
3.7               0.3%             73
3.3               0.1%             25
2.6               0.0%              1

```

**Comment by popravich** [comment]
Lets drop 3.4 as well

**Comment by asvetlov** [comment]
BTW Next aiohttp release will be limited to Python 3.5.3+

**Comment by popravich** [comment]
TODO:
* [ ] replace old-style `@asyncio.coroutine` with `async def`;
* [ ] update tests;
* [ ] rename py35_* tests;

**Comment by popravich** [comment]
Done.
