### ISSUE TITLE
How to close the connection in Sanic?

### ISSUE THREAD

**Issue by vg-pulsepoint** [aio-libs/aioredis#305]
I wrote a script that uses Sanic with aioredis,which keeps throws errors when I shutdown Sanic. The errors disappear when I remove the "after_server_stop" block below, but I would prefer to leave it in and close the connection properly. Please advise, both my code and error message are below and I'm running aioredis v0.3.3 and Sanic v0.6

	import os, datetime, logging
	from sanic import Sanic
	from sanic import response
	import asyncio
	import uvloop
	import aiohttp
	import aioredis
	from sanic.config import Config

	redis_host = os.environ.get('redis_host', "localhost")
	redis_port = int(os.environ.get('redis_port', 6379))

	Config.REQUEST_TIMEOUT = 120

	asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())

	app = Sanic(__name__)

	@app.listener('before_server_start')
	async def before_server_start(app, loop):
		app.redis_pool = await aioredis.create_connection( (redis_host, redis_port), loop=loop )

	@app.listener('after_server_stop')
	async def after_server_stop(app, loop):
		app.redis_pool.close()
		await app.redis_pool.wait_closed()

	@app.route('/fetch', methods=['POST'])
	async def handle_request(request):
		print(request.body)
		data = await app.redis_pool.execute('lrange', 'text', 0, -1)
		return response.json({"data": data})

	loop = asyncio.get_event_loop()

	app.run(host="0.0.0.0", port=5000, workers=4, debug=True)

This is the error message:

	Process Process-4:
	Traceback (most recent call last):
	  File "/Users/username/anaconda3/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
	    self.run()
	  File "/Users/username/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
	    self._target(*self._args, **self._kwargs)
	  File "/Users/username/anaconda3/lib/python3.6/site-packages/sanic/server.py", line 564, in serve
	    trigger_events(after_stop, loop)
	  File "/Users/username/anaconda3/lib/python3.6/site-packages/sanic/server.py", line 419, in trigger_events
	    loop.run_until_complete(result)
	  File "uvloop/loop.pyx", line 1201, in uvloop.loop.Loop.run_until_complete (uvloop/loop.c:25601)
	RuntimeError: Event loop stopped before Future completed.
	2017-10-19 15:28:07 - (sanic)[INFO]: Server Stopped

**Comment by jettify** [comment]
Sorry do not familiar with sanic, but I think sanic issue tracker is better place to ask. Looks likely error has nothing to do with aioredis. My best take is that `after_server_stop` event is not coroutine by sanic design.

**Comment by jin10086** [comment]
i use 
`loop = asyncio.get_event_loop()`
can work ,

**Comment by jin10086** [comment]
oh ,shit
sometime ok,sometime error
