### ISSUE TITLE
undistinguishable command future cancellation

### ISSUE THREAD

**Issue by sebbov** [aio-libs/aioredis#306]
The following two cases are indistinguishable from a caller's perspective, when using a reconnecting client:

1. The command future was externally (by the application, possibly a higher layer one) canceled:
https://github.com/honzasp/aioredis/blob/master/aioredis/connection.py#L169

2. The read had an otherwise unhandled exception (incl in our case an unexpected, externally (network/server) initiated connection reset, `ConnectionResetError` exception):
https://github.com/honzasp/aioredis/blob/master/aioredis/connection.py#L179
(The XXX may indicate remaining work in this area that concerns the issue at hand.)
In this case, the connection ends up being closed and the waiters / command futures cancelled (whereas the expectation here would be to have a non-`asyncio.CancelledError` set on the future).

In both cases, the future returned by `aioredis` will be observed to have been canceled.

In the case of a non-reconnecting (normal) client, a canceled future due to the above can differentiate between both 1. and 2. by looking at the `client.closed` attribute.  No such luck for a reconnecting client, which always announces `client.closed = False`. If the suggested fix above isn't doable, exposing the state of the wrapped connection (e.g. a `was_closed`) in the auto-reconnecting client would still be allow to make this differentiation, and thus provide a way out.

thanks!
-seb.

**Comment by popravich** [comment]
I'm not going to fix reconnecting client, as it has been deprecated and dropped in v1.0.
However I've fixed futures cancelling on disconnects, so its now possible to distinguish between
task cancellation and connection error.
The fix is in master branch but I will backport it to v0.3 branch soon.

**Comment by popravich** [comment]
Released with v0.3.5
