### ISSUE TITLE
Subscribe to same channel multiple times

### ISSUE THREAD

**Issue by DurandA** [aio-libs/aioredis#310]
When calling `subscribe()` on same connection multiple times, the message is available only on first wait_message() and is subsequently unavailable to other readers.

We can demonstrate it with a simple example:
```python
import asyncio
import aioredis

loop = asyncio.get_event_loop()

async def reader(ch):
    while (await ch.wait_message()):
        msg = await ch.get_json()
        print("Got Message:", msg)

async def main():
    pub = await aioredis.create_redis(
        ('localhost', 6379))
    sub = await aioredis.create_redis(
        ('localhost', 6379))
    res1 = await sub.subscribe('chan:1')
    ch1 = res1[0]
    res2 = await sub.subscribe('chan:1')
    ch2 = res2[0]

    tsk = asyncio.ensure_future(reader(ch1))
    tsk = asyncio.ensure_future(reader(ch2))

    res = await pub.publish_json('chan:1', ["Hello", "world"])

loop.run_until_complete(main())
loop.run_forever()
```

This output `Got Message: ['Hello', 'world']` once while I expected each reader to be able to get every message. Is this behavior intended?

**Comment by popravich** [comment]
Yes, this is intended behavior. aioredis creates one queue per channel per connection.
So if you want to have multiple readers for single channel you'll need to create some wrapper for this,
offhand, it can look like this:
```python
class MultiConsumerSingleProducer:
    def __init__(self, ch):
        self.ch = ch
        self.fut = None

    def __aiter__(self):
        return self

    async def __anext__(self):
        if self.fut is not None:
            return await self.fut
        self.fut = get_event_loop.create_future()
        msg = await self.ch.get_json()
        fut, self.fut = self.fut, None
        fut.set_result(msg)
        return msg

async def reader(mcsp):
    async for msg in mcsp:
        print(msg)
ch = ....
mcsp = MultiConsumerSingleProducer(ch)
ensure_future(reader(mcsp))
ensure_future(reader(mcsp))
...
```
(its just a sample code but it should work)
(of course it should be polished for production, because cancelling one reader would cancel all readers as they all wait for one future...)

**Comment by DurandA** [comment]
Thanks for the clarification. I came with a similar solution using `__anext__` but with an `asyncio.Event`. I prefer your pattern as I had to use a global async function. Thank you very much for coming up with this example.

**Comment by DurandA** [comment]
One last related question; does `psubscribe()` have the same behavior?

**Comment by popravich** [comment]
Yes
