### ISSUE TITLE
Protect master branch

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aioredis#318]
As we did for aiohttp.

A PR with failed tests cannot be merged.
PR without review cannot be merged (but @popravich as admin can ignore it :)
The most important thing is a button for re-merging the master is the master branch was updated after the last PR commit.

**Comment by popravich** [comment]
Updated.
* [x] PRs require review
* [x] PRs require travis  & appveyor green status

**Comment by asvetlov** [comment]
Thanks @popravich !
