### ISSUE TITLE
publish binary data will close the channel

### ISSUE THREAD

**Issue by DeoLeung** [aio-libs/aioredis#331]
a quick description
```python
data = ... # some binary data
conn.publish('channel', data) # will close all subscribed channels

# if we do a base64 on it, i works, though the data is still bytes
import base64
data = base64.64encode(data)
conn.publish('channel', data)
```

**Comment by popravich** [comment]
Everything within computer memory is a binary data, please provide at least one of the following:
* a stack trace showing error (if any);
* a simple runnable script to re-create the issue;

**Comment by DeoLeung** [comment]
I think it was my mistake to mixed some connection and pub/sub, closing util I could reproduce it
