### ISSUE TITLE
provide an option to install aioredis without hiredis

### ISSUE THREAD

**Issue by olexandr-klymenko** [aio-libs/aioredis#341]
In my case it is highly preferable not to install python3-dev package. I need to have an option to skip hiredis dependency

**Comment by asvetlov** [comment]
redis/hiredis-py#38 is the proper solution for the problem.

**Comment by asvetlov** [comment]
As a workaround you could build binary wheels yourself.

**Comment by popravich** [comment]
`pip install --no-deps aioredis`

**Comment by olexandr-klymenko** [comment]
Thanks

21 лист. 2017 р. 10:47 PM "Alexey Popravka" <notifications@github.com> пише:

**Comment by bukowa** [comment]
Can someone explain is there is noticable downside of not installing deps?
