### ISSUE TITLE
HISTORY.rst out of date

### ISSUE THREAD

**Issue by samuelcolvin** [aio-libs/aioredis#342]
Hi, please can you either keep `HISTORY.rst` up to date or remove it.

Preferably keep the file and keep it uptodate.

Having, but with nothing since 0.2.9 (2016-10-24) is not good.

**Comment by popravich** [comment]
Try `CHANGES.txt` its like `HISTORY.rst` but better ;)

**Comment by samuelcolvin** [comment]
Then maybe call if `CHANGES_OLD.rst` the current situation is very confusing.

Personally I'd prefer all changes to be in one place.

**Comment by popravich** [comment]
Fixed with 89c33baefa10c7198453876f8cb8b314498e8afe

**Comment by samuelcolvin** [comment]
thanks
