### ISSUE TITLE
Pipelining and connection sharing

### ISSUE THREAD

**Issue by samuelcolvin** [aio-libs/aioredis#343]
I'm finding the new magic with `Redis` hiding a connection pool slightly confusing.

If I do

```py
info, key_count = await asyncio.gather(redis.incr('foo'), redis.incr('foo'))
```

Am I guaranteed that both `incr` calls will use the same connection and be pipelined?

The docs are ambiguous: they say 

> execute every command on random connection

but also 

> Both tasks will send commands through same connection without acquiring (locking) it first.

Is the connection choice random or somehow grouped for a single task?

Or do I need to do

```py
    with await redis as r:
        info, key_count = await asyncio.gather(r.info(), r.dbsize())
```
?

**Comment by popravich** [comment]
Pipelining features is kept, but at some cost:
* connections list is rotated after each command,
so these two command may be sent through different connections if pool.size is greater than 1;
* grouping by task is not reliable — tornado has issue with asyncio tasks (need to check if its fixed already);
* also I'd like to make this logic a bit more smart, ie: pick a connection based on command info.

```python
with await redis as r:
    ....
```
This context manager must be used when you want to be sure that all commands are sent
through one connection; all other tasks using redis directly will not touch this connection.
This is especially important when you need to use blocking command,
in this case you should definitely send it through "isolated" connection

**Comment by samuelcolvin** [comment]
Thanks, you'll need to update the docs for pipelinging [here](http://aioredis.readthedocs.io/en/v1.0.0/mixins.html?highlight=pipeline#aioredis.commands.TransactionsCommandsMixin.pipeline)

**Comment by popravich** [comment]
That `pipeline` uses single connection to send all commands. What notes do you want me to put there?

**Comment by samuelcolvin** [comment]
```py
>>> #
>>> # The same can be done without pipeline:
>>> #
>>> fut1 = redis.incr('foo')    # the 'INCRY foo' command already sent
>>> fut2 = redis.incr('bar')
>>> await asyncio.gather(fut1, fut2)
[2, 2]
```

This is wrong, it should use an isolated connection.

**Comment by popravich** [comment]
Ok. I'll revise it
