### ISSUE TITLE
create_redis_pool will create extra thread when pass a host name need to be resolved

### ISSUE THREAD

**Issue by zpoint** [aio-libs/aioredis#356]
Whenever I pass **aioredis.create_redis_pool((host, port))** a **host name** need to be resolved instead of direct ip address, as soon as I call **create_redis_pool**, **htop** shows my current **python3** process will create an extra thread, If I set up with **uvloop**, Then 4 extra threads will be created.

**htop** shows after I call create_redis_pool("127.0.0.1", 6379)

![image](https://user-images.githubusercontent.com/18083296/34066267-4a1497ce-e247-11e7-96d0-3844ab0b22ff.png)

**htop** shows after I call create_redis_pool("localhost", 6379)

![image](https://user-images.githubusercontent.com/18083296/34066256-1e4b7680-e247-11e7-9a51-67e41a12669b.png)

**htop** shows after I call create_redis_pool("localhost", 6379) with **uvloop** installed

![image](https://user-images.githubusercontent.com/18083296/34066288-8db5a75c-e247-11e7-8f8f-f7f3701e687c.png)

#### Environment:
* Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-85-generic x86_64)
* Python 3.5.2
* pip package
    * aioredis (1.0.0)
    * tornado (4.5.2)
    * uvloop (0.9.1)
    * pip (9.0.1)

#### Simple server example

	import asyncio
	import uvloop
	import aioredis
	import tornado.web
	from tornado.platform.asyncio import AsyncIOMainLoop

	class TestHandler(tornado.web.RequestHandler):
	    async def get(self):
	        print("In get, passing 127.0.0.1")
	        await self.redis_test("127.0.0.1")
	        print("done with 127.0.0.1, going to sleep for 20s")
	        await asyncio.sleep(20)
	        print("In get, passing localhost")
	        await self.redis_test("localhost")
	        print("Done, going to sleep for 20s")
	        await asyncio.sleep(20)

	    async def redis_test(self, host):
	        pool = await aioredis.create_redis_pool((host, 6379))
	        keys = await pool.keys("*")
	        print(keys)

	def main():
	    server = tornado.httpserver.HTTPServer(tornado.web.Application([("/", TestHandler)]))
	    server.bind(20006)
	    #############################################
	    ### If installed with uvloop, four extra thread will be created
	    ### otherwise, one extra thread will be created
	    #############################################
	    # asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())
	    AsyncIOMainLoop().install()
	    server.start(1)
	    asyncio.get_event_loop().run_forever()

	if __name__ == "__main__":
	    main()

In command line:

     python3 test.py

Then, in another terminal

    curl "http://localhost:20006"

new thread created as the screenshots show,
is it normal ?

**Comment by hellysmile** [comment]
Yes, it is quite normal, cuz by default asynvcio uses threads to resolve hostname to ip address

You can use aiodns to resolve before passing params to aioredis.create_redis_pool , if extra thread is so critical for You

**Comment by zpoint** [comment]
Ok, I will try aiodns, Thanks!
