### ISSUE TITLE
support for ASYNC flushes

### ISSUE THREAD

**Issue by kamikaze** [aio-libs/aioredis#364]
Please add support for FLUSHDB ASYNC. Like redis.flushdb(async=True)

https://redis.io/commands/flushdb
https://redis.io/commands/flushall

**Comment by popravich** [comment]
Hi, @kamikaze,
This is trivial, would you make a PR?

**Comment by popravich** [comment]
TODO:
* [ ] update `flushdb/flushall` methods adding keyword-only argument `async` with default value `False`;
* [ ] update doc-strings describing parameter.
