### ISSUE TITLE
Sentinel pool discover doesn't take into account passed timeout

### ISSUE THREAD

**Issue by kamikaze** [aio-libs/aioredis#368]
https://github.com/aio-libs/aioredis/blob/fd7411a8a6313c1844f615ef26902bb38fcc5c7b/aioredis/sentinel/pool.py#L44

https://github.com/aio-libs/aioredis/blob/fd7411a8a6313c1844f615ef26902bb38fcc5c7b/aioredis/sentinel/pool.py#L196

**Comment by azkore** [comment]
👍

**Comment by popravich** [comment]
Would you make a PR?
