### ISSUE TITLE
Document user/password usage

### ISSUE THREAD

**Issue by XayOn** [aio-libs/aioredis#388]
DBUri usage in redis seems to not be so-well documented, it would be helpful to have it documented here.
It is a standard URI with auth in it, but I've seen some co-workers having trouble understanding it and might (even if it's a kinda-corner case, as most people don't use authentication) be helpful to have an example available.

In this case, wich is a bit  confusing is the form:

redis://:password@host:port/db

(the :password bit, it makes sense as it is an empty username, but as said, might be helpful to have in the docs and has no cost :-) )

**Comment by popravich** [comment]
Makes sense, thanks
