### ISSUE TITLE
confusion with context managers

### ISSUE THREAD

**Issue by marcstreeter** [aio-libs/aioredis#395]
I'm trying to migrate up from 0.3.3. Previously I had a context manager in place like so:

```
import aioredis
options = {
    'host': 'redis', 
    'port': 6379
}

class Eph:
    __slots__ = ("_conn", )
    _redis_host = None
    _redis_port = None
    _pool = None

    def __init__(self):
        self._conn = None

    async def __aenter__(self):
        pool = await self.get_pool()
        self._conn = await pool.acquire()
        return self._conn
 
    async def __aexit__(self, exc_type, exc_val, exc_tb):
        pool = await self.get_pool()
        pool.release(self._conn)
        self._conn = None

    async def get_pool(self):
        if not Eph._pool:
            Eph._pool = await aioredis.create_pool(
                (self.host, self.port),
                minsize=5,
                maxsize=10
            )
        return Eph._pool

    @property
    def host(self) -> str:
        return options['host']

    @property
    def port(self) -> int:
        return options['port']
```
I've looked through much of the documentation on migration and I'm missing something

Currently calling the above like so:

```
async with Eph() as eph:
   await eph.script_flush()
```

Results in 

```
...
AttributeError: 'RedisConnection' object has no attribute 'script_flush'
```

I realize that some of the objects that were once returned have changed.  My main goal is to free the connection after using it.  From the source code I've read, `_AsyncConnectionContextManager` seems to do what I want but I can't find it used anywhere except for some obscure `get` method which is also proving hard to locate its use. I guess I'm looking for guidance as to the recommended way to use this library since there seem to be so many different ways.  I'm comfortable with switching over to the following way of doing it

```
redis = await aioredis.create_redis_pool(
    ('localhost', 6379),
    minsize=1,
    maxsize=1)

async def task():
    # Shared mode
    await redis.set('key', 'val')
```

however it would necessitate me changing a lot of code that expects a context manager.

**Comment by popravich** [comment]
Hi @marcstreeter,

In v0.3 the connection was actually a `aioredis.commands.Redis` instance and in v1.0 it is now a real connection.
You can wrap it with `aioredis.commands.Redis` and it will act the same:
```python
from aioredis.commands import Redis
class Eph:
    async def __aenter__(self):
        pool = await self.get_pool()
        self._conn = Redis(await pool.acquire())
        return self._conn
```

**Comment by marcstreeter** [comment]
@popravich  thank you for the quick reply.  It works until `__aexit__` is hit where I now get:

'Invalid connection, maybe from other pool', <Redis <RedisConnection [db:0]>>

I thought I'd set it up so that the same pool is always retrieved.  Is there something glaringly wrong with my `__aexit__`?  Or has that changed as well?

**Comment by popravich** [comment]
oh, just save connection and wrap it on return:
```python
from aioredis.commands import Redis
class Eph:
    async def __aenter__(self):
        pool = await self.get_pool()
        self._conn = await pool.acquire()
        return Redis(self._conn)
```

**Comment by marcstreeter** [comment]
@popravich thank you so much .  This fixes it.
