### ISSUE TITLE
SPOP since 3.2 supports a count but that's not represented in library

### ISSUE THREAD

**Issue by marcoceppi** [aio-libs/aioredis#411]
I'm not sure the plan for what version cut off that this library aims to support, but being able to supply a count to `spop` would be great to have.

**Comment by popravich** [comment]
PR is welcome.
Tasks list:
* [ ] add count parameter to `spop`.
* [ ] add new tests
* [ ] update docstrings.

**Comment by stas-dubrovskyi** [comment]
I'll do this within next few days

**Comment by stas-dubrovskyi** [comment]
@KostSvitlana
