### ISSUE TITLE
`create_redis` with string `redis://localhost:6379/0` doesn't work anymore.

### ISSUE THREAD

**Issue by Natim** [aio-libs/aioredis#444]
It started to be broken since the last error. I now get the following **OSError**

```OSErrorasyncio.selector_events in _sock_connect
error[Errno 99] Cannot assign requested address```
```

```
address | ['10.0.10.4', 6379]
-- | --
fd | 28249
fut | <Future finished exception=OSError(99, 'Cannot assign requested address')>
self | <_UnixSelectorEventLoop running=True closed=False debug=False>
sock | <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
```

It might be because it is a list rather than a tuple. (Python 3.7)

**Comment by Natim** [comment]
I looked it up and the parse_url command haven't changed in since 10 months: https://github.com/aio-libs/aioredis/commit/d805165cf9000c31df73b6503d3b1219c23ac8ad

It seems really strange to me...

**Comment by gyermolenko** [comment]
@Natim hi
I couldn't reproduce your issue (aioredis 1.2.0, python3.7.1)
Please provide output or traceback after running this file 
```
import asyncio
import aioredis

asyncio.run(aioredis.create_redis("redis://localhost:6379/0"))
```

**Comment by Natim** [comment]
I couldn't reproduce. Closing.
