### ISSUE TITLE
new release with Py3.7 resolutions

### ISSUE THREAD

**Issue by dfee** [aio-libs/aioredis#457]
I came across this problem today after upgrading to 3.7: https://github.com/aio-libs/aioredis/issues/425

I noticed that this has been solved, but want to rely on a pypi release. Can we get a new release, or is there something we're holding out for?

Thanks!

**Comment by popravich** [comment]
I will do a new release this weekend.

**Comment by gjcarneiro** [comment]
Promises, promises... :P 

If you're unsure about master stability, then maybe making a release marked as beta, so that some of us can test but is strictly opt-in?

**Comment by popravich** [comment]
@gjcarneiro 
Ah, sorry((( busy days(
Its almost there

**Comment by popravich** [comment]
@gjcarneiro , @dfee , @adamcharnock, aioredis v1.2.0 has been just released, please try it out!

**Comment by adamcharnock** [comment]
Amazing! Thanks @popravich, looking forward to taking this for a spin.
