### ISSUE TITLE
Why is context manager returning from "await connection" not closing the connection?

### ISSUE THREAD

**Issue by hubo1016** [aio-libs/aioredis#463]
In current version, when not using connection pool, you must explictly close a connection to prevent it from leaking.
```python
with (await connection) as conn:
    ...
```
do nothing. Is it by design?

**Comment by popravich** [comment]
> Is it by design?

Yes. However you confused `Redis` instance with `RedisConnection` instance.
I believe the `connection` in your example is a `Redis` instance, not the lower-level
`RedisConnection` which does not implement context manager interface.
This `with await... as conn:` is a legacy interface that was used in connections pool up to v0.3.
At that point connections pool didn't implement `execute` method and to send a command you
had to explicitly acquire a connection and execute command on it.
This behavior was kept to make easier transition between v0.3 and v1.0

In current (v1.x) version, if client is created with `create_redis()` `with await client as conn:` is basically a "no operation"; if client is created with `create_redis_pool()` the context manager will return a new `Redis` instance bound to some connection from pool and release it on exit (this is needed if you want to send some blocking commands).

**Comment by hubo1016** [comment]
@popravich So currently it is not possible to manage a single connection with a context manager?

**Comment by popravich** [comment]
Yes, however if you need this behavior you can either use the following construction or make it a context manager:
```python
redis = await aioredis.create_redis(...)
try:
    # main program code
finally:
    redis.close()
    await redis.wait_closed()
```
