### ISSUE TITLE
calling aioredis.create_redis_pool before main loop is started

### ISSUE THREAD

**Issue by schlitzered** [aio-libs/aioredis#493]
Hello

as soon as i call aioredis.create_redis_pool(**kwargs) the function is trying to contact the a redis server.

this fails because when i create the pool, the asyncio loop is not yet running.

right now i am helping myself by delaying the creating of the connection pool after the loop is running.
but now i have to check in every function trying to use the pool, if the pool is already created.

is there a way to create a connection pool, that will only create a redis connection when something is requesting it?

Kind Regards

**Comment by asvetlov** [comment]
-1. 
aioredis objects are coupled with a loop instance, therefore their lifecycle should be shorter than event loop running time.

**Comment by gjcarneiro** [comment]
Agree, aio libs require the loop for everything they do, it's not a big deal, and the assumption simplifies code and testing.
