### ISSUE TITLE
mset function signature improvements

### ISSUE THREAD

**Issue by suvorovalexander** [aio-libs/aioredis#500]
https://github.com/aio-libs/aioredis/blob/10ac4cb80f164f57ae4ea19ee06e5e532a7893db/aioredis/commands/string.py#L139

according to the function signature in order to set key1->1, key2->2, key3->3 I would need to call it as following
`redis.mset(key1, 1, key2, 2, key3, 3)`

Shouldn't it be accepting a mapping instead which is more intuitive way of passing key->value pairs?

**Comment by popravich** [comment]
resolved by #580
