### ISSUE TITLE
Add the "MKSTREAM" option to xgroup_create

### ISSUE THREAD

**Issue by dcecile** [aio-libs/aioredis#503]
It's a not-yet-documented option for creating consumer groups before the stream exists: https://github.com/antirez/redis/issues/4824#issuecomment-438263421

Example signature for `StreamCommandsMixin`:
```py
    def xgroup_create(self, stream, group_name, latest_id='$', mkstream=False):
```

**Comment by gyermolenko** [comment]
I would like to tackle this (if nobody else has started)

p.s. Hey @dcecile sorry if I interrupt and you wanted to make it yourself

**Comment by dcecile** [comment]
@gyermolenko :) No problem, I haven't started it, so feel free to go ahead
