### ISSUE TITLE
Add a BUSYGROUP reply error

### ISSUE THREAD

**Issue by dcecile** [aio-libs/aioredis#504]
The XGROUP CREATE command can return a BUSYGROUP error when a group already exists: https://redis.io/commands/xgroup

I think the `ReplyError` subclass for matching it would look like this:

```py
class BusyGroupError(ReplyError):
    MATCH_REPLY = "BUSYGROUP Consumer Group name already exists"
```

**Comment by gyermolenko** [comment]
@popravich hi
I would like to tackle this (if nobody else has started)
