### ISSUE TITLE
Do I need to add await wait_closed() all the time?

### ISSUE THREAD

**Issue by yorushika** [aio-libs/aioredis#506]
For example, just like README:
```
loop = asyncio.get_event_loop()

async def go():
    conn = await aioredis.create_connection(
        'redis://localhost', loop=loop)
    await conn.execute('set', 'my-key', 'value')
    val = await conn.execute('get', 'my-key')
    print(val)
    conn.close()
    await conn.wait_closed()
loop.run_until_complete(go())
```

If I just delete the line `await conn.wait_closed()`, will the connection be closed at last?

I'm considering sometimes I don't need to wait until the connection closed, I just need to read some data from redis and then if I need *another* data I can call a function like that above again. So after several procedures like this, will *these* connections close? Also, when? Are there any problem hidding?

**Comment by popravich** [comment]
Hi @yorushika ,
If you remove `wait_closed` the connection will get closed.
The `wait_closed` is, basically, waits until responses reader task is stopped.
It happens on the next event loop iteration after `close()` method is called.

**Comment by yorushika** [comment]
> Hi @yorushika ,
> If you remove `wait_closed` the connection will get closed.
> The `wait_closed` is, basically, waits until responses reader task is stopped.
> It happens on the next event loop iteration after `close()` method is called.

Thanks! That helps a lot!
