### ISSUE TITLE
select() max file descriptors

### ISSUE THREAD

**Issue by Fux002** [aio-libs/aioredis#519]
Does the implementation use the Select() statement and therefore has limitations to 1024 file descriptors?

Thx a lot!

**Comment by asvetlov** [comment]
Any system which communicates via sockets needs at least one file descriptor to do it.
`aioredis` is not an exception.
You can raise 1024 limit for your process if needed. The Internet has plenty of instructions on how to do it.

`aioredis` is built on top of asyncio. In turn, asyncio uses select/poll/epoll/kqueue/iocp depending on used operation system.

**Comment by Fux002** [comment]
Than you for the reply.

The problem with Linux and select is they the maximum number of file descriptors is 1024 raising the open file limits will not help.

Do you have a solution?

Please see below. 
https://linux-tips.com/t/is-it-possible-to-listen-file-descriptor-greater-than-1024-with-select/45

**Comment by asvetlov** [comment]
Did you try to use google search?
https://unix.stackexchange.com/questions/85457/how-to-circumvent-too-many-open-files-in-debian

**Comment by Fux002** [comment]
Thx for the reply!
Yes lots. As far as I understand the select.select() can not manage more that 1024 file descriptors. Therefore it’s suggested to use select.poll() or select.epoll()

Is the library able to use this or is it easy to convert it to use this?

**Comment by asvetlov** [comment]
Well, `select` has compile-time limitation for open file handlers.
Not asyncio uses the best fit selector, e.g. `epoll` on Linux.
As I said, `aioredis` itself doesn't select poller method but respects asyncio choice.
So, on Linux, it is `epoll` by default. You may want to increase the amount of available file descriptors for your process, the link provided by me earlier has comprehensive enough how-to instructions.

I hope it helps.
I'm going to close the issue, it is not related to aioredis itself.
Feel free to ask more if needed.
