### ISSUE TITLE
Support for Redis v5.0.3?

### ISSUE THREAD

**Issue by SuperSajuuk** [aio-libs/aioredis#551]
Hi. I noticed on the docs that aioredis does not appear to officially support Redis v5.0.3 yet. I use Redis for an automoderator bot on Discord and planning to update the Redis server version (it's on 3.2.10 right now), and just wondering: will aioredis work just fine with the latest stable build, or might I experience errors doing this? Thanks for the help in advance!

**Comment by f0ff886f** [comment]
I have been using aioredis with redis 5.0.3 without issue.

**Comment by SuperSajuuk** [comment]
@f0ff886f I missed your post but yep, aioredis works fine on all current versions of Redis. I'm on v6.0.8 atm and no issues. I was just curious about whether the library will support all newer features that Redis are implementing, but presumably it will in time 👍
