### ISSUE TITLE
xread with non-integer timeout argument hangs indefinitely

### ISSUE THREAD

**Issue by tino** [aio-libs/aioredis#567]
The `timeout` argument [is passed verbatim to redis](https://github.com/aio-libs/aioredis/blob/master/aioredis/commands/streams.py#L252). When that argument is not an integer, the XREAD will hang.

Example:
`await r.xread(["system_event_stream"], timeout=0.1, latest_ids=[0])` shows up in `redis monitor` as `1554191321.856104 [3 172.18.0.16:58130] "XREAD" "BLOCK" "0.1" "STREAMS" "system_event_stream" "0"` and hangs forever.

It's probably best to assert the argument is an integer. Other python functions often accept seconds for timeouts, so a warning/error would be good.

**Comment by popravich** [comment]
Fixed in #582
