### ISSUE TITLE
How to help?

### ISSUE THREAD

**Issue by felipevolpone** [aio-libs/aioredis#58]
I want to help this project but I don't know what are the features that you've in mind! There is some way to we talk or list that describe what must be done?

**Comment by popravich** [comment]
Hi, @felipevolpone 
You can always start with tests coverage.
Server commands have not been tested fully and we need some tests to, atleast, be sure that there are no typos.

As for new features -- I need to think it over.

**Comment by felipevolpone** [comment]
Hey @popravich, sounds great! 
I'm thinking to use unittest and py.test to start the process to coverage the library. It's ok?

**Comment by asvetlov** [comment]
@felipevolpone no py.test please.
Just use

    $ make cov

for running coverage tool

**Comment by popravich** [comment]
-1 for py.test
We already have unittests and just a bit custom script to run them.
You can run tests with `make test` or `make cov` commands, or
directly by running `python3 runtest.py`

**Comment by popravich** [comment]
Most library code is covered with tests, only [ServerCommandsMixin](https://github.com/aio-libs/aioredis/blob/master/aioredis/commands/server.py) is not tested well.
