### ISSUE TITLE
subscribe pattern example

### ISSUE THREAD

**Issue by jamesstidard** [aio-libs/aioredis#588]
Hi,

I'm currently using `aioredis` to subscribe to channels within my application. I want to switch to a pattern but having issues understanding the example code and docs (probably because I'm not that familiar with Redis in general).

Here's what I currently have for subscribing to a specific channel:

```python
redis = await aioredis.create_redis(**kwargs)
channel, = await redis.subscribe("SOME_CHANNEL")

while await channel.wait_message():
    data = await channel.get()
```

I've tried a bunch of variations to try and replace the "SOME_CHANNEL" with something more like "*" but I've not had any success. Replacing with "*" returns a channel that if I inspect has the `is_pattern` flag set to false.

I've also tried using `aioredis.Channel("*", pattern=True)` as an argument to `subscribe` as well.

Would appreciate some pointers of what I'm misunderstanding. 

Thanks.

**Comment by popravich** [comment]
Hi,

You must use `psubscribe` method instead of `subscribe`:
* https://aioredis.readthedocs.io/en/v1.2.0/mixins.html#aioredis.commands.PubSubCommandsMixin.psubscribe
* https://redis.io/commands/psubscribe
```python
redis = await aioredis.create_redis(**kwargs)
pattern, = await redis.psubscribe("SOME_*")  # read all channels prefixed with `SOME_`

while await pattern.wait_message():
    data = await pattern.get()
```

**Comment by jamesstidard** [comment]
Ah, fantastic, thank you. 

I spent too long trying to figure this one out. It seems obvious now...

Thanks again @popravich.
