### ISSUE TITLE
Feature: connect from url.

### ISSUE THREAD

**Issue by schlitzered** [aio-libs/aioredis#589]
Hi

it would be nice if it would be possible to implement a function that will parse a "redis url" and return a connection / pool object that matches the url, i have something like this implemented for in https://github.com/schlitzered/pyredis.

here is the documentation on how this works:

https://pyredis.readthedocs.io/en/latest/example.html#getting-pool-by-url

and here the related source code:

https://github.com/schlitzered/pyredis/blob/master/pyredis/__init__.py#L36

it is more or less a  convenience thing for configuration files.

since redis has many different ways in how it could be setup, this would allow to have a unified config file option called redis_url, where you simply pass an url.

if anyone else agrees that this is should be in here, i could also implement this for aioredis & create a pull request.

Kind Regards,

**Comment by popravich** [comment]
aioredis support Redis URL scheme, please take a look at example code in docs:
https://aioredis.readthedocs.io/en/v1.2.0/api_reference.html#connection
https://aioredis.readthedocs.io/en/v1.2.0/api_reference.html#connections-pool
