### ISSUE TITLE
PubSub noticable delay

### ISSUE THREAD

**Issue by schlitzered** [aio-libs/aioredis#590]
hi,

i noticed that there is a pretty high delay for pubsub stuff. it takes something between 500ms and 1000ms for a published message to be parsed and output by aioredis.

this is not happening when i publish a message using redis-cli, and subscribe messages using redis-cli, there the message arrives within a few ms.

environment:
Ubuntu linux 18.04,
redis 4.0.9

redis cli, redis-server and aioredis running on the same host.

how to reproduce:

redis server is running on localhost.

aioredis_dummy.py

```
import asyncio
import aioredis


def main():
    loop = asyncio.get_event_loop()

    async def reader(ch):
        while await ch.wait_message():
            msg = await ch.get_json()
            print("Got Message:", msg)

    async def go():
        sub = await aioredis.create_redis(
            ('localhost', 6379))
        res = await sub.subscribe('chan:1')
        ch1 = res[0]

        tsk = asyncio.ensure_future(reader(ch1))

        await tsk

    loop.run_until_complete(go())


if __name__ == '__main__':
    main()
```

console 1: run the script:
```
python3 aioredis_dummy.py
```
console 2: run redis-cli subscribe
```
 redis-cli subscribe 'chan:1'
```

console 3: publish a message:
```
redis-cli PUBLISH chan:1 '{"blarg": "blub"}'
```

have all 3 consoles side by side, so you can see the output. you will notice that the redis-cli command receives the message more or less instantly, where there is a noticeable delay using the aioredis test script.

**Comment by popravich** [comment]
Sorry, I can't reproduce this
