### ISSUE TITLE
Differences between aioredis and asyncio-redis

### ISSUE THREAD

**Issue by benjolitz** [aio-libs/aioredis#60]
Asyncio-redis is a fairly complete and mature asynchronous redis implementation. I'm curious as to what sets aioredis apart from it?

https://github.com/jonathanslenders/asyncio-redis

**Comment by popravich** [comment]
Oh, well)
* First of all I tried to make it simplier -- asyncio_redis implements `asyncio.Protocol` (lots of code) vs aioredis uses `asyncio.StreamReader`/`StreamWriter` (no protocol code; just *read & send*);
* At the moment when I started aioredis asyncio-redis had no `hiredis` parser.
* asyncio_redis API forces end-user to work with one type of data, ie only bytes or only unicode or etc. So you would receive an error trying to mix data types, say `set('unicode_key', b'encoded_bytes_data')`.
* asyncio-redis has no way to execute raw command
* "automatic reconnections", well, in asyncio-redis if the server has gone away would reconnect, reconnect and reconnect. I mean reconnection is done as soon as connection is lost which is bad. For instance we had functional tests infrastructure where we were starting & shutting down standalone redis server instance so after all tests we had several hundreds of spamy errored 'reconnect' messages.
* aioredis doesn't have pub/sub yet, but it is in progress and will be implemented soon.

**Comment by lux-lth** [comment]
How does aioredis handle disconnections ?

I'm having trouble with asyncio-redis not closing connections.
Redis says it has reached the max number of clients. But most of them are ghosts.

Do you think aioredis is better at handling those ?

Also, does aioredis support `async with` ?
