### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by f0ff886f** [aio-libs/aioredis#626]
Any chance we can get a new release? There have been so many new fixes, its a shame to keep it away from folks on PyPi :)

Thank you for the great library.

**Comment by adamcharnock** [comment]
I would really appreciate a new release too. I have both client code and [Lightbus](https://lightbus.org) which are dependent upon aioredis and they are running into some bugs that were merged a while back (i.e. #605)

Thank you for the library and – in particular – all the effort that goes into maintenance and releases 👍

**Comment by rubik** [comment]
I need a new relase too. The latest version from PyPI is almost a year old and there's a ton of stuff that is only on GitHub. For example, in the PyPI version `spop` does not even support the `count` parameter!

**Comment by bsergean** [comment]
The github version has xlen for working with streams, which isn't in the last PyPI version. I'd love a new version too. The workaround is to use xinfo which returns the stream length.

Thanks for the great library !

**Comment by popravich** [comment]
v1.3.0 has been released

**Comment by bsergean** [comment]
Thanks Alexey !!
