### ISSUE TITLE
can't set expiry for keys 

### ISSUE THREAD

**Issue by ajay1mg** [aio-libs/aioredis#630]
I am on aioredis 1.2.0 and trying to set expiry for keys using the below syntax:

```
async def get_pool(self):
    if not self._pool:
        with (await self._lock):
            if not self._pool:
                self._pool = await aioredis.create_pool((self._host, self._port), minsize=self._minsize,
                                                        maxsize=self._maxsize)
    return await self._pool

async def set_key(self, key, value, namespace=None, expire=0):
    with (await self.get_pool()) as redis:
        if namespace is not None:
            key = self._get_key(namespace, key)
        await redis.execute('set', key, value, expiry=30)
```

This is the error which I get when I use expiry in execute for set:

TypeError: execute() got an unexpected keyword argument 'expiry'

however, I can do it by using `expireat` method like:

```
timestamp = int((datetime.datetime.now() + datetime.timedelta(0, expire)).timestamp())       
await asyncio.ensure_future(redis.execute('expireat', key, timestamp))
```

Is there a way to set expiry in a single call with `await redis.execute('set', key, value)` or is this an issue?

**Comment by him3010** [comment]
facing the same issue

**Comment by vijay-saini** [comment]
Facing the same issue

**Comment by popravich** [comment]
Hi, @ajay1mg 
You are using `RedisConnection.execute` method ([see the docs](https://aioredis.readthedocs.io/en/v1.3.0/api_reference.html#aioredis.RedisConnection.execute)) which does not have `expiry` keyword argument.
Replace your command with the following:
```python
await redis.execute('set', key, value, 'ex', 30)
```
(https://redis.io/commands/set)
