### ISSUE TITLE
"@coroutine" decorator is deprecated since Python 3.8

### ISSUE THREAD

**Issue by youngminz** [aio-libs/aioredis#648]
When I test my program using `aioredis==1.3.0` with pytest in Python 3.8.0, I get the following warning:

```
=============================== warnings summary ===============================
/.../lib/python3.8/site-packages/aioredis/abc.py:35
  /.../lib/python3.8/site-packages/aioredis/abc.py:35: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def wait_closed(self):

/.../lib/python3.8/site-packages/aioredis/abc.py:96
  /.../lib/python3.8/site-packages/aioredis/abc.py:96: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def acquire(self):  # TODO: arguments

/.../lib/python3.8/site-packages/aioredis/abc.py:133
  /.../lib/python3.8/site-packages/aioredis/abc.py:133: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def get(self):

-- Docs: https://docs.pytest.org/en/latest/warnings.html
```

Since Python 3.5+ supported by the aioredis supports the `async def` keyword, it seems to be fine to change the `@asyncio.coroutine` decorator to `async def`. 

[Python 3.5 Documentation](https://docs.python.org/3.5/library/asyncio-task.html#coroutines):

> The async def type of coroutine was added in Python 3.5, and is recommended if there is no need to support older Python versions.

**Comment by youngminz** [comment]
`loop` parameter is deprecated too. It's better to get rid of this together. 

```
DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
```

**Comment by youngminz** [comment]
The loop parameter is so heavily used throughout the test that finding and removing it from the test can be a huge task. 

![image](https://user-images.githubusercontent.com/5145369/66889419-4bec3580-f01d-11e9-95f1-2dcf68028f04.png)

Also, the `@pytest.mark.run_loop` decorators that make up the event loop seem to need modification. I haven't looked at it in detail, but `@pytest.mark.run_loop` seems to be incompatible with the `asyncio.get_event_loop()` function. I will check for any changes that require further changes.

**Comment by popravich** [comment]
Hi, @youngminz , no problem at all, please finish the `coroutine` PR and after that we can remove `loop` step-by-step, first from main code, then from tests, fixtures, etc.

**Comment by youngminz** [comment]
Ok, I got it!

**Comment by l1n** [comment]
I see that the feature branch has been merged, is it possible to do a release now?

**Comment by popravich** [comment]
I'm preparing release, will make it in 4-8 hours

**Comment by popravich** [comment]
Sorry, guys, another busy day, need some more time.

**Comment by popravich** [comment]
v1.3.1 is out there!
