### ISSUE TITLE
Losing pub/sub messages while using channel.wait_message()

### ISSUE THREAD

**Issue by JanBednarik** [aio-libs/aioredis#66]
When I use `channel.wait_message()` I'm losing pub/sub messages.

It's easy to replicate this bug. Run in one terminal window subscribing script:

```python
import aioredis
import asyncio

@asyncio.coroutine
def main():
    red = yield from aioredis.create_redis(('localhost', 6379))
    channel, = yield from red.subscribe('foo')
    num = 0
    while (yield from channel.wait_message()):
        msg = yield from channel.get()
        print(num, msg)
        num += 1

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

In second one terminal window run publishing script:

```python
import aioredis
import asyncio

@asyncio.coroutine
def main():
    red = yield from aioredis.create_redis(('localhost', 6379))
    for i in range(100000):
        yield from red.publish('foo', i)
        print(i)

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

Publishing script will finish with `99999` but subscribing script with much less number (e.g. `80340`).

If you change `while (yield from channel.wait_message()):` to `while True:` in subscribing script it will finish with `99999` without any problem.

Python 3.4.3
OS X 10.10.3

**Comment by popravich** [comment]
Thanks for the report. I will look into.
