### ISSUE TITLE
aioredis scan command example

### ISSUE THREAD

**Issue by pryg-skok** [aio-libs/aioredis#67]
Hello,

Can you please show me how to use one of SCAN command with aioredis? I understand how use with simple redis and without asyncio, but here I can't figure out how to iterate over elements.
It would be very helpful.

Thank you!

**Comment by popravich** [comment]
Try like this:
```python
cur = b'0'
while cur:  # on first iteration `cur` evaluates to True value
    cur, keys = yield from redis.scan(cur)
    # at this point `cur` can be 0 (integer) marking end of scan so while loop will stop.
    for key in keys:
        print(key)
```

**Comment by pryg-skok** [comment]
Thank you very much. It works.
