### ISSUE TITLE
wait_ok always failed when connection's encoding is used

### ISSUE THREAD

**Issue by zamoa** [aio-libs/aioredis#70]
_testutil.py

    class RedisEncodingTest(BaseTest):
        def setUp(self):
            super().setUp()
            self.redis = self.loop.run_until_complete(self.create_redis(
                ('localhost', self.redis_port), loop=self.loop, encoding='utf-8'))

        def tearDown(self):
            del self.redis
            super().tearDown()

string_commands_test.py

    class StringCommandsEncodingTest(RedisEncodingTest):
        @run_until_complete
        def test_set(self):
            ok = yield from self.redis.set('my-key', 'value')
            self.assertTrue(ok)

            with self.assertRaises(TypeError):
                yield from self.redis.set(None, 'value')

util.py

    @asyncio.coroutine
    def wait_ok(fut):
        res = yield from fut
        if res == b'QUEUED':
            return res
        return res == b'OK'

In wait_ok, fut's result is 'OK', not b'OK'.
so res == b'OK' is always False
maybe res == b'QUEUED' is always False

**Comment by kernel0** [comment]
wait_convert, wait_make_dict do the same

**Comment by popravich** [comment]
The fix is in master.
Will release with cluster commands update
