### ISSUE TITLE
create_redis_pool().subscribe() returns 'list' if only one variable is assigned

### ISSUE THREAD

**Issue by TrulyBright** [aio-libs/aioredis#717]
The code below doesn't cause any error:
```
pool = aioredis.create_redis_pool('redis://localhost')

async def main():
  ch1, ch2 = await pool.subscribe('channel:1', 'channel:2')
  assert isinstance(ch1, aioredis.Channel)
  assert isinstance(ch2, aioredis.Channel)
```
But if only one channel is assigned by subscribe(), AsserionError occurs.
```
async def main():
  ch1 = await pool.subscribe('channel:1')
  print(type(ch1)) # <class 'list'>
  assert isinstance(ch1, aioredis.Channel) # AssertionError
```
Currently I need to make 'dummy' channels to use only one. Please fix the bug.

__EDIT__: fixed some typo

**Comment by ElusiveSpirit** [comment]
@TrulyBright That does not look like a bug. Subscribe method returns a list as it documented, so you need an extra comma to handle it with a single variable. Please take a look into [example](https://github.com/aio-libs/aioredis/blob/52c26a9c1c8263d8d2c76948d8333fb7e9f1b865/examples/getting_started/05_pubsub.py#L8).
