### ISSUE TITLE
Python3.8 Support: change of asyncio.locks.Lock

### ISSUE THREAD

**Issue by jeffguorg** [aio-libs/aioredis#726]
hi

aioredis==1.2.0 raised an exception like this
```
  File "/opt/env/lib/python3.8/site-packages/aioredis/pool.py", line 261, in _wait_execute
    conn = await self.acquire(command, args)
  File "/opt/env/lib/python3.8/site-packages/aioredis/pool.py", line 325, in acquire
    async with self._cond:
  File "/usr/local/lib/python3.8/asyncio/locks.py", line 97, in __aenter__
    await self.acquire()
  File "/opt/env/lib/python3.8/site-packages/aioredis/locks.py", line 20, in acquire
    if not self._locked and all(w.cancelled() for w in self._waiters):
TypeError: 'NoneType' object is not iterable
```

and i digged around and found that aioredis.locks.Lock inherits asyncio.locks.Lock, and in python3.8, asyncio.locks.Lock no longer set a default waiters deque in ```__init__``` method. thus we need a fix

ref: 
- https://github.com/python/cpython/commit/9aa78566fbeeb8cdaa669ad22f92cf63765f4135#diff-c64956880a9946d21fcb56aac4ef041c
- https://github.com/python/cpython/pull/13834

**Comment by ar4hc** [comment]
i think there nned to be a chnage in in in `_wake_up_first` too. But not sure how. Just ignore the loop if no _waiters give an follow up error in `connection.py:177` [tested using the sample usage script from arq](https://github.com/samuelcolvin/arq/issues/174) ...

**Comment by jeffguorg** [comment]
> i think there nned to be a chnage in in in `_wake_up_first` too.

yes. and i'm not sure how. i see that in asyncio it looks like:
```python
    def _wake_up_first(self):
        """Wake up the first waiter if it isn't done."""
        if not self._waiters:
            return
        try:
            fut = next(iter(self._waiters))
        except StopIteration:
            return

        # .done() necessarily means that a waiter will wake up later on and
        # either take the lock, or, if it was cancelled and lock wasn't
        # taken already, will hit this again and wake up a new waiter.
        if not fut.done():
            fut.set_result(True)
``` 
i have little experience in this. i think we could just use this piece of code or do it simply by
```python
        def _wake_up_first(self):
            """Wake up the first waiter who isn't cancelled."""
            for fut in (self._waiters or []):
                if not fut.done():
                    fut.set_result(True)
                    break
```

and sorry to bother. but i'm pretty new here. it seems like my pr cannot pass the CI checks. does that matter? what should i do?

cc @popravich

**Comment by Catastropha** [comment]
Python3.8 support is needed, can anyone help solve issues

**Comment by Andrew-Chen-Wang** [comment]
@jeffguorg @ar4hc It seems like all our problems are with that one function `_read_data`. My log error:
```
'Task was destroyed but it is pending!\ntask: <Task pending coro=<RedisConnection._read_data() running at /usr/local/lib/python3.7/site-packages/aioredis/connection.py:186> wait_for=<Future cancelled> cb=[RedisConnection.__init__.<locals>.<lambda>() at /usr/local/lib/python3.7/site-packages/aioredis/connection.py:168]>'
```
Unfortunately, they all could be different errors, too. For example, mine somehow ended up here: https://github.com/aio-libs/aioredis/blob/8a207609b7f8a33e74c7c8130d97186e78cc0052/aioredis/stream.py#L79 and it seems like that's what happens on connection, too. Connecting still works, but it gets annoying to always see that message.

**Comment by zgoda** [comment]
@Andrew-Chen-Wang I had the same issue, close connection before shutting down application loop. In aiohttp it's done by adding a close handler to `on_cleanup` list.

**Comment by rafa-acioly** [comment]
Is there a solution to this already? i'm facing the same problem.
