### ISSUE TITLE
xdel(stream, id) can only delete one id each time?

### ISSUE THREAD

**Issue by lttzzlll** [aio-libs/aioredis#737]
redis official xdel can delete many ids each time, but aioredis can only delete one id each time. why aioredis differ from official redis.

aioredis
```
xdel(stream, id)
Removes the specified entries(IDs) from a stream
```

redis
```
XDEL key ID [ID ...]
```

https://redis.io/commands/xdel

https://aioredis.readthedocs.io/en/v1.3.0/mixins.html#aioredis.commands.StreamCommandsMixin.xdel

**Comment by allyo-dmytro-smyk** [comment]
@lttzzlll any updates on this?
