### ISSUE TITLE
Will the repository be maintained?

### ISSUE THREAD

**Issue by abersheeran** [aio-libs/aioredis#747]

**Comment by zgoda** [comment]
Most probably no.

https://www.youtube.com/watch?v=Yq46oeK_JDQ

**Comment by shaqarava** [comment]
It will be. Rather, it will probably always either be this one or one of the other two ([aredis](https://github.com/NoneGG/aredis) or [asyncio-redis](https://github.com/jonathanslenders/asyncio-redis)). When a repo falls too far behind, other people will either take it over or decide to put work towards one of the others (Or create anew).

This repo is the most popular so I would bet on it. If I ran into a problem with it and had to fix it myself, I would. Just today I submitted a feature request for rejson support. If it doesn't happen, I'll end up either adding it myself or adding it to one of the other async redis modules (Whichever is easier). I begin by using the interface methods which as we know is the first step to a new feature.

**Comment by zgoda** [comment]
I'm sorry to say but aredis benchmark is either wrong or there's no point in async redis client at all. :D

**Comment by shaqarava** [comment]
> I'm sorry to say but aredis benchmark is either wrong or there's no point in async redis client at all. :D

I've never used the others. I just heard of them.

**Comment by qeternity** [comment]
This library doesn't have cluster support, and has a different API that redis-py whereas aredis sticks much more closely to being an async version of redis-py.

**Comment by bsergean** [comment]
For what it's worth I wrote an asyncio library with cluster support -> https://github.com/machinezone/rcc/
However aredis looks like the best bet if you need cluster support.

**Comment by seandstewart** [comment]
Hello, I'm taking on maintainership of this repository and calling on the community for help in getting it updated. If you have any free time or good will left to give, I'd appreciate your help! 

#822
