### ISSUE TITLE
xread returns nothing

### ISSUE THREAD

**Issue by shaqarava** [aio-libs/aioredis#750]
Redis 6.0.3
Python: 3.8.2
aioredis: 1.3.1

Nothing is returned by xread in aioredis. redis-cli returns the stream properly.

```
import asyncio
import aioredis

loop = asyncio.get_event_loop()


async def main():
    stream = 'chennai'
    fields = {
        'foo': 'bar'
    }


    redis = await aioredis.create_redis('redis://localhost', loop=loop)
    await redis.xadd(stream, fields)
    result = await redis.xread([stream])
    print(result)
    redis.close()
    await redis.wait_closed()

loop.create_task(main())
```

**Comment by art1415926535** [comment]
You need to pass `latest_ids` argument.

```python
result = await redis.xread([stream], latest_ids=['0000000000000-0'])
```

Also use `asyncio.run(main())` (python 3.7+) instead of explicitly creating a loop.

**Comment by shaqarava** [comment]
> You need to pass `latest_ids` argument.
> 
> ```python
> result = await redis.xread([stream], latest_ids=['0000000000000-0'])
> ```
That's weird. I thought I had tried that. Anyway, It's working. Thanks.
> 
> Also use `asyncio.run(main())` (python 3.7+) instead of explicitly creating a loop.
That's just because I'm testing in a jupyter notebook. Can't use `run`.

**Comment by shaqarava** [comment]
Sorry for re-opening. Why doesn't `$` work? I'm trying to draw parallels between the Redis tutorial and this library so I know what I'm doing.
