### ISSUE TITLE
ZRANGEBYLEX does not handle min of "+" or max of "-"

### ISSUE THREAD

**Issue by bmerry** [aio-libs/aioredis#784]
The code for handling the special values `+` and `-` in zrangebylex only handles `-` for `min` and `+` for max, not vice versa. For example, the following code prints `[b'bar']` instead of an empty list:

```python
import asyncio
import aioredis

async def main():
    client = await aioredis.create_redis_pool('redis://localhost')
    await client.zadd('foo', 0.0, 'bar')
    result = await client.zrangebylex('foo', b'+', b'+')
    print(result)
    client.close()
    await client.wait_closed()

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
loop.close()
```

This also affects `zrevrangebylex` and `zremrangebylex`.

Incidentally, the API design is problematic because it's impossible to pass strings like `(-` (meaning, strings lexicographically greater than `-`) into redis.

**Comment by seandstewart** [comment]
@bmerry -

Thanks for this submission! Would you be willing to contribute a potential fix to the API? Maintenance of this library is back on and the next release will be a breaking change, so updating the API to work as expected would be a great boon.

**Comment by bmerry** [comment]
Yes, I may be able to contribute something, depending on the timeframe. When are you thinking of releasing the next version?

**Comment by bmerry** [comment]
@seandstewart I can think of two possibilities for eliminating the ambiguity. I'm going to start on the first, but let me know if you'd rather I did the second.

1. Eliminate the `include_min` and `include_max` arguments, and make it the user's responsibiity to prepend a `[` or `(`. This will break almost all code that uses these APIs, but it will break them in a way that gives an error message. It will also make the implementation simpler as it will just be forwarding to redis.

2. Introduce singleton constants meaning "from the start" / "from the end", similar to `ZSET_AGGREGATE_SUM` etc; and treat `"-"` and `"+"` as literal strings which will get a prefix. This will keep a lot of code working as is (any code that doesn't explicitly pass a `-` or `+`), but code that breaks will break subtly (e.g. will start excluding anything that comes before "-" lexicographically.
