### ISSUE TITLE
Task was destroyed but it is pending; in wait_make_dict

### ISSUE THREAD

**Issue by sanlem** [aio-libs/aioredis#787]
Hello!
After adding this function I've started seeing errors. Code:
```python
async def fetch_last_data(count: int, redis: aioredis.Redis) -> List[Entry]:
    try:
        all_data_key = f"something:*"
        keys = await redis.keys(all_orders_key)

        pipe = redis.pipeline()
        for k in keys:
            pipe.hgetall(k)

        keys = sorted(keys, key=lambda x: int(x.split(":")[-1]))

        if len(keys) > count:
            keys = keys[-count:]

        pipe = redis.pipeline()
        for k in keys:
            pipe.hgetall(k)

        raw_data = await pipe.execute()
        return parse_redis_data(raw_data)
    except:
        log.error(f"FetchLastData count={count}: {str(sys.exc_info()[0])} {str(sys.exc_info()[1])}")
```
I've seeing many errors like this:
`2020-07-31 17:26:45,434 asyncio  [MainThread] ERROR Task was destroyed but it is pending!
task: <Task pending name='Task-563' coro=<wait_make_dict() done, defined at /Users/v.franchuk/src/fix38/lib/python3.8/site-packages/aioredis/util.py:65> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x10cf61fd0>()]>>`

I have no idea where does it come from. This function is awaited. Could you help me, please?

**Comment by TECHNOFAB11** [comment]
This often happens when a task was created but the program ended (/more specifically the event loop closed). Your program probably ends too fast, either aioredis was working on something or it couldn't clean up and stop everything fast enough.

**Comment by seandstewart** [comment]
This is likely an issue with the current deserialization implementation, which wraps all calls in an asynchronous data-structure. If there's an exception during deserialization, it seems we're not properly cleaning up after ourselves...

**Comment by greshilov** [comment]
I guess the problem is in `try/except` block. In provided code it's broad enough to catch `asyncio.CancelledError`, what leads to forgotten dangling tasks in background.

When garbage collector consumes task, which is not done yet, it logs `Task was destroyed but it is pending: ...`

**Comment by seandstewart** [comment]
Ah yes, I believe @greshilov is correct. @sanlem in your `try/except` block, you should explicitly catch and and re-raise any CancelledError.

JFYI it's very bad practice to use a black `except`.

```python
async def fetch_last_data(count: int, redis: aioredis.Redis) -> List[Entry]:
    try:
        all_data_key = f"something:*"
        keys = await redis.keys(all_orders_key)

        pipe = redis.pipeline()
        for k in keys:
            pipe.hgetall(k)

        keys = sorted(keys, key=lambda x: int(x.split(":")[-1]))

        if len(keys) > count:
            keys = keys[-count:]

        pipe = redis.pipeline()
        for k in keys:
            pipe.hgetall(k)

        raw_data = await pipe.execute()
        return parse_redis_data(raw_data)

    except (SystemExit, KeyboardInterrupt, asyncio.CancelledError) as err:
        log.info(f"Got external shutdown: {err.__class__.__name__}: {err}")
        raise

    except Exception:
        log.error(f"FetchLastData count={count}: {str(sys.exc_info()[0])} {str(sys.exc_info()[1])}")
```
