### ISSUE TITLE
Explicit passing of coroutine objects to asyncio.wait() is deprecated since Python 3.8

### ISSUE THREAD

**Issue by tirkarthi** [aio-libs/aioredis#789]
Following warnings are reported while running the tests in Python 3.10

```
tests/sentinel_commands_test.py: 20 warnings
tests/sentinel_failover_test.py: 6 warnings
  /root/checked_repos/aioredis/aioredis/sentinel/pool.py:210: DeprecationWarning: The explicit passing of coroutine objects to asyncio.wait() is deprecated since Python 3.8, and scheduled for removal in Python 3.11.
    done, pending = await asyncio.wait(tasks,
```

**Comment by seandstewart** [comment]
@tirkarthi thanks for looking into this! 

Maintenance is currently underway to resolve these sorts of problems and make aioredis ready for the latest versions of Python. We've dropped Python3.5 support as of the last few days and will be looking for contributors who are willing to help us out. Would you be willing to contribute a potential fix for this issue?
