### ISSUE TITLE
No Updates or Releases Since 2019

### ISSUE THREAD

**Issue by seandstewart** [aio-libs/aioredis#820]
I believe this library may have been abandoned (intentionally or not). 

The maintainer (@popravich) has not committed to any GitHub project since releasing v1.3.1 in December of 2019. As of submitting this issue, there are 48 open pull requests and 96 issues, dating back to the beginning of this year. 

@asvetlov do you have the ability to reach out to the current maintainer? Would you be able to mark another maintainer of the project if the current maintainer cannot be reached? I tag you as I know you're heavily involved in the `aio-libs` project, so perhaps you may have more administrative tools than others.

Would anyone be willing to take on the mantle of maintainership? I don't ask this lightly, as I have a few small projects which I maintain and I understand the time commitment. I hate to see such a good library fade into dust, however.

**Comment by asvetlov** [comment]
Heh, time is the main question.

Does anybody want to pick the flag up?

**Comment by seandstewart** [comment]
@asvetlov I don't have a lot of free time, but I'm happy to pick up the flag in a temporary, maintenance-only mode, at least to get the package up-to-date and moving again.

I can't promise feature work, but if folks are willing to submit PRs, I'm happy to review.

We're also going to need to look at transferring ownership of the PyPI package so that releases can be published.: https://pypi.org/project/aioredis/

**Comment by asvetlov** [comment]
@seandstewart the invitation with admin rights is sent.

What is your account name on PyPI?

**Comment by seandstewart** [comment]
@asvetlov my PyPI account name is `seandstewart`!

**Comment by asvetlov** [comment]
The invite is sent

**Comment by asvetlov** [comment]
I believe there is nothing to do with this PR --- @seandstewart is the project admin now with all required privileges.

P.S.
@seandstewart just a suggestion. 
Please feel free to give the 'write' access to folks who contributed a few "good and merged" pull requests.
