### ISSUE TITLE
Drop Python 3.5 support

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aioredis#824]
Python 3.5 was a famous release (async/await syntax was introduced) but the version has reached end-of-life.
We can (and should) drop it.
Speaking as the maintainer of other libraries, I can say that it simplifies the code base a little

**Comment by seandstewart** [comment]
Agreed - I was surprised to see it still supported.

I do worry that dropping a language version likely means a major version bump, as that's definitely a breaking change, but it's a worthwhile one.
