### ISSUE TITLE
Reformat with black

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aioredis#825]
I use black for my daily job for 2 years, my team is happy with it.

aiohttp passed this bar recently. CPython is in the discussion.
Sure, every developer has the own code style which is better than proposed by black.
On another hand, autoformatted code doesn't look ugly, it is okay at least.

The real reason is that: autoformatting drops all discussions about the styling.
New contributors should not learn the code style used by the project, they just learn how to run `black` before pushing a PR.
The bar is lowered.

@seandstewart do you have objections for adopting this tool?

**Comment by seandstewart** [comment]
Yes - I think this issue, along with #826 would be excellent additions for developers - I use black on all of my projects and all of the projects at my employer and I've found it extremely helpful in the same way you mention.
