### ISSUE TITLE
Drop "at least one approval" policy for the main branch

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aioredis#828]
The idea is good in general but

1. We have an underpowering situation for the project.  If somebody with the commit rights made a PR -- I personally trust this person and don't want to make additional barriers for merging.
2. Even CPython has no such policy -- we, Python Core Dev trust each other. We are adults. Plus, the merged PR can be reverted at any time.

@seandstewart do you have an objection?

**Comment by seandstewart** [comment]
I do not - I generally agree with your sentiment on this.

**Comment by asvetlov** [comment]
Done
