### ISSUE TITLE
Migrating from asyncio-redis to aioredis

### ISSUE THREAD

**Issue by fmhall** [aio-libs/aioredis#897]
Hello,

We have been using asyncio-redis for some time now, but want to switch over to aioredis for a number of reasons. However, our code implements the RedisProtocol found here:

https://asyncio-redis.readthedocs.io/en/latest/pages/reference.html

and some methods like `smembers_asset` don't exist in aioredis. I thought at first we could use the `connection_cls=asyncio_redis.Connection` parameter on an aioredis connection pool to expose this protocol, but that fails as their `Connection` object doesn't inherit the `aioredis.Connection` abc class.

Has anyone migrated before, and know the path forward?

Thanks.

**Comment by Andrew-Chen-Wang** [comment]
It's true some things aren't in aioredis, but smembers_asset isn't a command in Redis. `smembers` is the command you're looking for, and aioredis has that. All asyncio-redis did with `smembers_asset` is run `smembers` and convert the result to a Python set. Take a look at our examples, i.e. our test:

https://github.com/aio-libs/aioredis/blob/8c6cb22e1606d75f15066d0e3725d9505e24b90b/tests/set_commands_test.py#L196-L212

If the command is missing, use the low level connection example: https://aioredis.readthedocs.io/en/v1.3.1/examples.html#low-level-connection-usage-example

Hope that helps!
