### ISSUE TITLE
My value is stored as a number. Why does it become a string after being taken out with .get()? 

### ISSUE THREAD

**Issue by jianmaikj** [aio-libs/aioredis#898]
```
key = 'id'
value = 111
await redisdb.set(key, value)
res = await redisdb.get(key)
print(res, type(res))
```
![image](https://user-images.githubusercontent.com/75167751/107110124-5d93c500-6880-11eb-8eae-664d0164d5da.png)

Is there a way to keep the number type?
Thanks

**Comment by Andrew-Chen-Wang** [comment]
As expected: https://github.com/aio-libs/aioredis/blob/8c6cb22e1606d75f15066d0e3725d9505e24b90b/tests/string_commands_test.py#L220-L234

All in all, you can do something like this (from [django-async-redis](https://github.com/Andrew-Chen-Wang/django-async-redis/blob/master/django_async_redis/serializers/pickle.py)):

```python
import pickle
from typing import Any

from django.core.exceptions import ImproperlyConfigured

from .base import BaseSerializer

class PickleSerializer(BaseSerializer):
    def __init__(self, options):
        self._pickle_version = -1
        self.setup_pickle_version(options)

    def setup_pickle_version(self, options):
        if "PICKLE_VERSION" in options:
            try:
                self._pickle_version = int(options["PICKLE_VERSION"])
            except (ValueError, TypeError):
                raise ImproperlyConfigured("PICKLE_VERSION value must be an integer")

    def dumps(self, value) -> bytes:
        return pickle.dumps(value, self._pickle_version)

    def loads(self, value) -> Any:
        return pickle.loads(value)
```

Don't worry about base serializer. Nothing is actually in there.

What you can do is add a util function or use some kind of class as a helper to decode: https://github.com/Andrew-Chen-Wang/django-async-redis/blob/7aae00e632d8677738d77a1e717ba53b5c5c0143/django_async_redis/client/default.py#L354-L367

**Comment by SuperSajuuk** [comment]
Bit late but worth pointing out that Redis doesn't really have a concept of integers as far as I've determined. Anything involving integers will be converted to string automatically. Using set only stores "strings", so if something is an integer, it gets converted before being stored, hence why your returned value from get() is now a string. You will just have to know which keys will be a pure integer and then cast them to a Python integer.

Side note: I wouldn't recommend using Pickle for this kind of thing, seems a bit unnecessary. Just test your key for whether it returns None (meaning it doesn't exist) or convert to int in your code when it does.

**Comment by MojixCoder** [comment]
@Andrew-Chen-Wang but what about other data types?  
For example model data types, etc.  
How Django understand that what type of data we have stored in cache?

**Comment by Andrew-Chen-Wang** [comment]
@MojixCoder That's the point of pickling; Python will convert whatever you've got to a byte stream. When deserializing, or unpickling from the cache, we're "unwrapping" that bytestream to have your original object. That's why you can cache model objects if you've ever used django-redis.

**Comment by MojixCoder** [comment]
@Andrew-Chen-Wang Pickling is working great. Thanks for your early response and help.
