### ISSUE TITLE
Remove hmset in aioredis

### ISSUE THREAD

**Issue by SuperSajuuk** [aio-libs/aioredis#905]
According to Redis documentation, hmset is deprecated as of v4 and people should use hset with variable key/value pairs. However, I think aioredis still assumes hset is a single key -> value so I cannot use hset with a variable key/value dictionary on my Redis 6.0.9 instance. Merging the functionality of hmset and hmset_dict into hset (and potentially removing hmset entirely) would make the library conform to the deprecation of hmset, although this would break the library for hmset pre v4. Probably worth including in the v2 library anyway.

**Comment by Andrew-Chen-Wang** [comment]
PR would be helpful!

**Comment by SuperSajuuk** [comment]
> PR would be helpful!
Unfortunately, I'm not very experienced in GitHub so I don't know how to make PR's and wouldn't want to touch this lib to do so :D

**Comment by Andrew-Chen-Wang** [comment]
@SuperSajuuk No worries. Actually in #846, the solution has actually already been merged but aioredis has not published a new release. You can pip install a specific git hash hopefully though if you really need it. Otherwise, closing.
