### ISSUE TITLE
pubsub docs problems

### ISSUE THREAD

**Issue by samuelcolvin** [aio-libs/aioredis#91]
There are a few problems with the [pub/sub docs](http://aioredis.readthedocs.org/en/latest/start.html#pub-sub-mode):

* the example doesn't run, not even nearly. I guess it should be more like the [example](https://github.com/aio-libs/aioredis/blob/master/examples/pubsub.py) in the examples directory.
* `asyncio.async` is depreciated in favour of `asyncio.ensure_future`
* `async_reader2` is defined by never use, i guess the last line should be using it.

**Comment by popravich** [comment]
> the example doesn't run, not even nearly. I guess it should be more like the example in the examples directory.

Those examples was intended to demonstrate the way to work with pub/sub;

> `asyncio.async` is depreciated in favour of `asyncio.ensure_future`

This is true for Python 3.4.4+. This is a bit harder to change 'cause `aioredis` claims to support Python 3.3

> async_reader2 is defined by never use, i guess the last line should be using it.

And again, it's just to demonstrate an idea.

**Comment by popravich** [comment]
I can add a link to examples page. Will that make it more clear?

**Comment by samuelcolvin** [comment]
I get that it's just demonstrating an idea, but this example (unlike the other examples) is pretty baffling if you come to it cold. The working example was much clearer for me.

I'm pretty sure the last line has a type and should be referencing `async_reader2`.

A link to the example would be good but for me the code in the docs is more confusing than helpful, why not just replace it with the example?

**Comment by popravich** [comment]
ok, I see your point.
