### ISSUE TITLE
Allow pubsub_numsub to accept the aioredis.Channel instances

### ISSUE THREAD

**Issue by paulefoe** [aio-libs/aioredis#913]
If that's would be a nice addition to the library, I'm willing to work on it.

I can also search through other methods of Pub/Sub to ensure that all of the methods accept the `aioredis.Channel` instances where appropriate.

**Comment by Andrew-Chen-Wang** [comment]
We are going to be updating this package dramatically in #891 . Let us know if this feature is still not implemented in that updated PR!

**Comment by paulefoe** [comment]
It seems there is no more `aioredis.Channel`. Everything is a string now, so I guess that issue should be closed
