### ISSUE TITLE
Add encoding parameter to sort command

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aioredis#96]
Decoding given array is useful feature. What do you think about?

**Comment by popravich** [comment]
Its a tricky question.
decoding is good, but you can construct `SORT` to get keys and values by reference
and what if you don't want to decode part of keys or
there may be more keys causing decode errors slowing response processing...
I don't see simple solution right now.

**Comment by asvetlov** [comment]
Good point. Actually we need a bunch of encoders -- first for *key* and encoders for every *get_patterns*. 
Final method signature becomes a mess easy.
Feel free to close as WontFix if you agree.

**Comment by popravich** [comment]
Wont fix
