### ISSUE TITLE
Create a gitter.im account for the repo

### ISSUE THREAD

**Issue by brunsgaard** [aio-libs/aioredis#98]
From Wikipedia

> Gitter is an instant messaging and chat room system for developers and users of GitHub repositories.

I first encountered it af https://github.com/biosustain/potion, see how the readme on github has a gitter link, I think this project could benefit from a gitter. What do you guys think?

**Comment by popravich** [comment]
Hi, I will think of it.
Any way you can ask any questions here or on [google groups]
(https://groups.google.com/forum/#!forum/aio-libs)

**Comment by brunsgaard** [comment]
@popravich Thanks ;)

**Comment by asvetlov** [comment]
I thought about giiter but declined the idea.
IFAIK gitter cannot be coupled to organization.
There is no reason for having separate gitter room for every aio-libs project.
Thus please post your question to aio-libs google group.

**Comment by brunsgaard** [comment]
I see, thank you for regarding my proposal.

**Comment by AlJohri** [comment]
@asvetlov you may consider creating an aio-libs/aio-libs repository which just lists the different projects going on and also has the Gitter.im channel

**Comment by popravich** [comment]
Yep, but gitter also has some nice integration features like "activity" etc and those are linked to repository (to its issues/comments/pull requests/etc)
