### ISSUE TITLE
Cumbersome to create a pool of reconnecting connections

### ISSUE THREAD

**Issue by brunsgaard** [aio-libs/aioredis#99]
Right now it is a bit cumbersome to create a pool of reconnecting connections, this is due to
https://github.com/aio-libs/aioredis/blob/3a69dc876338207c4605439319703427c2614738/aioredis/pool.py#L169

This could be improved

**Comment by asvetlov** [comment]
Please elaborate.

**Comment by popravich** [comment]
Anyway, why would you need a pool of reconnecting connections?
Main idea behind pool is to manage connections -- drop closed & create new.
Have you tried [reconnecting redis](http://aioredis.readthedocs.org/en/latest/api_reference.html#aioredis.create_reconnecting_redis)?

**Comment by brunsgaard** [comment]
@popravich, I have misunderstood the connection pool, if a connection is closed due to network failure etc, will the current implementation of the pool then discard it and create a new one seamlessly?

**Comment by popravich** [comment]
Yes, it will create new one.

Closed (disconnected) connections would not be a problem as long as connections from pool are used for short lived actions, ie:
```python
# Bad
with (yield from redis_pool) as redis:
    # inside this block a single connection bound to redis variable
    while True:
        data = yield from wait_long_time_for_data()
        yield from redis.set(key, data)

# Good
while True:
    data = yield from wait_long_time_for_data()
    with (yield from redis_pool) as redis:
        yield from redis.set(key, data)
```

**Comment by brunsgaard** [comment]
Okay, Thank you for the feedback.
